export type IndustryId = "technology" | "retail" | "manufacturing" | "food" | "services" | "logistics";
export type SegmentId = "budget" | "mainstream" | "premium" | "enterprise";
export type CompetitorArchetype = "cost_leader" | "premium_specialist" | "fast_follower" | "innovator" | "aggressive_entrant" | "conservative_incumbent";
export type LifecycleStage = "launch" | "validation" | "survival" | "growth" | "scale" | "maturity" | "crisis" | "failure";
export type EventKind = "macro" | "supply" | "labor" | "demand" | "regulation" | "competition" | "capital";

export interface Rng { next(): number }
export interface Macro { inflation:number; interestRate:number; growth:number; unemployment:number; consumerConfidence:number; businessConfidence:number; commodityIndex:number; creditAvailability:number }
export interface Industry { id:IndustryId; capitalIntensity:number; laborIntensity:number; marginTarget:number; elasticity:number; competition:number; growth:number; supplierConcentration:number; regulation:number }
export interface Segment { id:SegmentId; size:number; priceSensitivity:number; qualitySensitivity:number; brandSensitivity:number; switchingCost:number; loyalty:number; purchaseFrequency:number; incomeSensitivity:number }
export interface Supplier { id:string; capacity:number; unitCost:number; quality:number; leadTime:number; reliability:number; relationship:number; paymentTrust:number }
export interface Competitor { id:string; archetype:CompetitorArchetype; cash:number; share:number; price:number; quality:number; marketing:number; capacity:number; risk:number; capitalAccess:number; timeHorizon:number }
export interface Investor { id:string; capital:number; risk:number; horizon:number; relationship:number }
export interface Business {
  cash:number; revenue:number; expenses:number; debt:number; inventory:number; employees:number; skills:number; morale:number; workload:number; reputation:number; satisfaction:number; share:number; customers:number; churn:number; awareness:number; stage:LifecycleStage; valuation:number; lastProfit:number;
  product:{ price:number; quality:number; brand:number; availability:number; service:number; delivery:number; unitCost:number; capacity:number }
}
export interface Memory { price:number; quality:number; service:number; delivery:number; trust:number; loyalty:number; purchases:number }
export interface WorldEvent { id:string; kind:EventKind; day:number; severity:number; remaining:number; cause:string }
export interface Effect { source:string; target:string; magnitude:number; explanation:string }
export interface World {
  day:number; seed:number; version:number; macro:Macro; industry:Industry; segments:Segment[]; suppliers:Supplier[]; competitors:Competitor[]; investors:Investor[]; workforce:{laborSupply:number; wageIndex:number; skillAvailability:number}; capital:{creditAvailability:number; baseRate:number; riskPremium:number; investorRiskAppetite:number}; regulation:{pressure:number; complianceCost:number; shockRisk:number}; business:Business; memory:Record<SegmentId,Memory>; events:WorldEvent[]; effects:Effect[]
}
export interface Decision { price?:number; qualityInvestment?:number; marketing?:number; hiring?:number; training?:number; capacityInvestment?:number; rdInvestment?:number; borrowing?:number; repayment?:number; ethicsInvestment?:number }

const clamp=(x:number,a=0,b=100)=>Math.max(a,Math.min(b,x));
const nn=(x:number)=>Number.isFinite(x)?Math.max(0,x):0;
const industries:Record<IndustryId,Industry>={
 technology:{id:"technology",capitalIntensity:55,laborIntensity:70,marginTarget:22,elasticity:1.2,competition:78,growth:8,supplierConcentration:35,regulation:42},
 retail:{id:"retail",capitalIntensity:35,laborIntensity:65,marginTarget:10,elasticity:1.7,competition:88,growth:4,supplierConcentration:55,regulation:45},
 manufacturing:{id:"manufacturing",capitalIntensity:82,laborIntensity:62,marginTarget:15,elasticity:1.1,competition:68,growth:3,supplierConcentration:72,regulation:60},
 food:{id:"food",capitalIntensity:45,laborIntensity:78,marginTarget:9,elasticity:1.5,competition:82,growth:3,supplierConcentration:64,regulation:70},
 services:{id:"services",capitalIntensity:25,laborIntensity:88,marginTarget:18,elasticity:1,competition:65,growth:5,supplierConcentration:28,regulation:35},
 logistics:{id:"logistics",capitalIntensity:72,laborIntensity:72,marginTarget:12,elasticity:1.15,competition:70,growth:5,supplierConcentration:48,regulation:55},
};
const segments:Segment[]=[
 {id:"budget",size:30,priceSensitivity:.95,qualitySensitivity:.35,brandSensitivity:.25,switchingCost:.2,loyalty:35,purchaseFrequency:1.15,incomeSensitivity:.8},
 {id:"mainstream",size:40,priceSensitivity:.65,qualitySensitivity:.6,brandSensitivity:.55,switchingCost:.35,loyalty:50,purchaseFrequency:1,incomeSensitivity:.55},
 {id:"premium",size:20,priceSensitivity:.3,qualitySensitivity:.9,brandSensitivity:.85,switchingCost:.5,loyalty:65,purchaseFrequency:.8,incomeSensitivity:.4},
 {id:"enterprise",size:10,priceSensitivity:.2,qualitySensitivity:.95,brandSensitivity:.75,switchingCost:.85,loyalty:70,purchaseFrequency:.55,incomeSensitivity:.3}
];

export function createRng(seed:number):Rng{let s=seed>>>0;return{next(){s=(Math.imul(1664525,s)+1013904223)>>>0;return s/4294967296}}}
export function createWorld(seed=1,industry:IndustryId="technology"):World{
 const memory=Object.fromEntries(segments.map(s=>[s.id,{price:50,quality:50,service:50,delivery:50,trust:50,loyalty:s.loyalty,purchases:0}])) as Record<SegmentId,Memory>;
 return {day:1,seed:seed>>>0,version:3,macro:{inflation:3,interestRate:5,growth:3,unemployment:5,consumerConfidence:70,businessConfidence:68,commodityIndex:100,creditAvailability:75},industry:{...industries[industry]},segments:segments.map(s=>({...s})),suppliers:[{id:"supplier-a",capacity:500,unitCost:55,quality:78,leadTime:3,reliability:88,relationship:50,paymentTrust:70},{id:"supplier-b",capacity:700,unitCost:61,quality:90,leadTime:5,reliability:94,relationship:45,paymentTrust:70}],competitors:[{id:"cost",archetype:"cost_leader",cash:80000,share:12,price:88,quality:60,marketing:45,capacity:500,risk:45,capitalAccess:75,timeHorizon:55},{id:"premium",archetype:"premium_specialist",cash:120000,share:9,price:135,quality:88,marketing:70,capacity:350,risk:35,capitalAccess:85,timeHorizon:75},{id:"follower",archetype:"fast_follower",cash:60000,share:7,price:105,quality:68,marketing:50,capacity:300,risk:55,capitalAccess:60,timeHorizon:50}],investors:[{id:"investor-a",capital:250000,risk:65,horizon:70,relationship:40},{id:"investor-b",capital:500000,risk:35,horizon:85,relationship:35}],workforce:{laborSupply:70,wageIndex:100,skillAvailability:72},capital:{creditAvailability:75,baseRate:5,riskPremium:4,investorRiskAppetite:65},regulation:{pressure:45,complianceCost:3,shockRisk:8},business:{cash:20000,revenue:0,expenses:0,debt:0,inventory:100,employees:8,skills:60,morale:70,workload:45,reputation:50,satisfaction:65,share:1,customers:100,churn:4,awareness:35,stage:"launch",valuation:20000,lastProfit:0,product:{price:100,quality:65,brand:35,availability:90,service:65,delivery:90,unitCost:55,capacity:120}},memory,events:[],effects:[]};
}

function macroStep(m:Macro,i:Industry,r:Rng):Macro{const shock=(r.next()-.5)*.8;const pressure=m.growth*.08+(m.commodityIndex-100)*.015-(m.unemployment-5)*.08;const inflation=clamp(m.inflation+pressure*.25+shock*.05,0,20);const rate=clamp(m.interestRate+(inflation+1.5-m.interestRate)*.18,.5,18);const growth=clamp(m.growth+(m.consumerConfidence-60)*.025-(rate-5)*.11+i.growth*.08+shock,-10,12);const unemployment=clamp(m.unemployment-growth*.07+(rate-5)*.03,1,25);const confidence=clamp(m.consumerConfidence+growth*.5-inflation*.18-unemployment*.08+shock,10,95);const business=clamp(m.businessConfidence+growth*.55-rate*.12-inflation*.1,10,95);return{inflation,interestRate:rate,growth,unemployment,consumerConfidence:confidence,businessConfidence:business,commodityIndex:clamp(m.commodityIndex+pressure*.7+shock*2,55,180),creditAvailability:clamp(m.creditAvailability+business*.03-rate*.18-(m.creditAvailability-70)*.03,15,95)}}
function demand(w:World):number{const avg=w.competitors.reduce((s,c)=>s+c.price,0)/Math.max(1,w.competitors.length);return w.segments.reduce((sum,s)=>{const rel=w.business.product.price/Math.max(1,avg);const price=Math.exp(-s.priceSensitivity*w.industry.elasticity*(rel-1));const quality=.65+s.qualitySensitivity*w.business.product.quality/100*.7;const brand=.65+s.brandSensitivity*w.business.product.brand/100*.7;const economy=.75+.25*w.macro.consumerConfidence/100+s.incomeSensitivity*w.macro.growth/100*.08;const mem=w.memory[s.id];return sum+s.size*price*quality*brand*clamp(w.business.product.availability/100,.2,1)*economy*(.8+mem.trust*.003+mem.loyalty*.002)},0)}
function event(w:World,r:Rng):WorldEvent|null{const p=.006+(100-w.macro.consumerConfidence)*.0002;if(r.next()>=p)return null;const kinds:EventKind[]=["macro","supply","labor","demand","regulation","competition","capital"];const kind=kinds[Math.floor(r.next()*kinds.length)];const severity=25+r.next()*65;const duration=3+Math.floor(r.next()*12);return{id:`event-${w.day}-${kind}`,kind,day:w.day,severity,remaining:duration,cause:`${kind} conditions changed through interacting world variables`}}
function competitorStep(c:Competitor,b:Business,m:Macro):Competitor{const n={...c};if(c.archetype==="cost_leader")n.price=clamp(c.price+(Math.min(c.price,b.product.price*.94)-c.price)*.45,20,500);if(c.archetype==="premium_specialist")n.quality=clamp(c.quality+(b.product.quality>c.quality?1.2:.4));if(c.archetype==="fast_follower"){n.price=c.price+(b.product.price-c.price)*.3;n.quality=c.quality+(b.product.quality-c.quality)*.22}if(c.archetype==="innovator")n.quality=clamp(c.quality+.8);if(c.archetype==="aggressive_entrant"){n.price=clamp(c.price-.6);n.marketing=clamp(c.marketing+1)}if(c.archetype==="conservative_incumbent"&&m.growth<0)n.cash+=250;return n}
function stage(b:Business):LifecycleStage{if(b.cash<0||b.debt>Math.max(1000,b.revenue*.5))return"failure";if(b.cash<Math.max(1000,b.revenue*.05)||b.churn>15||b.morale<30)return"crisis";if(b.revenue<5000)return b.customers<150?"validation":"launch";if(b.share<3)return"survival";if(b.share<10)return"growth";if(b.share<25)return"scale";return"maturity"}
function valuation(b:Business,m:Macro,i:Industry):number{const margin=b.revenue>0?b.lastProfit/b.revenue:0;const growth=1+clamp(m.growth/100,-.1,.15);const risk=1+clamp((b.reputation-50)/500-b.debt/Math.max(1,b.cash+b.debt)*.35,-.35,.2);return Math.max(0,(b.cash-b.debt*.5+Math.max(0,b.lastProfit)*(8+i.growth*.2)+Math.max(0,b.revenue*(.35+margin*2)))*growth*risk)}

export function stepWorld(input:World,d:Decision={},rng:createRng(1)|Rng):{state:World;effects:Effect[];report:string[]}{
 let w=structuredClone(input);const e:Effect[]=[];const report:string[]=[];w.day++;w.macro=macroStep(w.macro,w.industry,rng);const ev=event(w,rng);if(ev)w.events.push(ev);for(const x of w.events)x.remaining--;w.events=w.events.filter(x=>x.remaining>0);if(ev)report.push(`Event: ${ev.kind} (${ev.severity.toFixed(0)}/100)`);
 const b={...w.business,product:{...w.business.product}};const oldPrice=b.product.price;b.product.price=clamp(d.price??oldPrice,1,10000);const qi=nn(d.qualityInvestment),mk=nn(d.marketing),rd=nn(d.rdInvestment),ci=nn(d.capacityInvestment),training=nn(d.training),hiring=d.hiring??0,borrow=nn(d.borrowing),repay=Math.min(nn(d.repayment),b.debt),ethics=nn(d.ethicsInvestment);
 b.product.quality=clamp(b.product.quality+qi*.025+rd*.018-.12);b.product.brand=clamp(b.product.brand+mk*.018+ethics*.01);b.reputation=clamp(b.reputation+ethics*.03);b.awareness=clamp(b.awareness+mk*.025-.3);b.product.capacity=Math.max(10,b.product.capacity+ci*.06);b.debt+=borrow-repay;b.cash+=borrow-repay;
 const wagePressure=clamp(100-w.workforce.laborSupply+b.reputation*.15);const actualHire=hiring*(.45+w.workforce.skillAvailability/200);b.employees=Math.max(0,b.employees+actualHire);b.morale=clamp(b.morale+training*.5-Math.max(0,b.workload-65)*.18);b.skills=clamp(b.skills+training*.45+actualHire*(w.workforce.skillAvailability-50)*.015);b.workload=clamp(b.workload+actualHire*2-training*.5);w.workforce.laborSupply=clamp(w.workforce.laborSupply-actualHire*.4);w.workforce.wageIndex=clamp(w.workforce.wageIndex+wagePressure*.01);
 const required=Math.ceil(b.product.capacity*.55);let remaining=required,cost=0,supplied=0;for(const s of [...w.suppliers].sort((a,z)=>a.unitCost-z.unitCost)){const units=Math.min(remaining,s.capacity*s.reliability/100);remaining-=units;supplied+=units;cost+=units*s.unitCost}const coverage=required?supplied/required:1;const output=Math.max(0,Math.min(b.product.capacity,supplied)*clamp((b.skills+b.morale)/180,.25,1.1)*(1-Math.min(.18,(100-b.skills)/700+Math.max(0,b.workload-75)/900)));b.inventory+=output;b.product.availability=clamp(50+coverage*50-Math.max(0,b.workload-80)*.4);
 const baseDemand=demand({...w,business:b});const pressure=w.competitors.reduce((s,c)=>s+Math.max(0,c.marketing-40)*.003+Math.max(0,c.quality-b.product.quality)*.004,0);const sold=Math.min(b.inventory,baseDemand*(1-clamp(pressure,0,.55)));const revenue=sold*b.product.price;const unitCost=b.product.unitCost*(w.macro.commodityIndex/100)*(1+w.macro.inflation/250);const payroll=b.employees*w.workforce.wageIndex*1.15;const interest=b.debt*(w.macro.interestRate+4)/36500;const variable=sold*unitCost;const op=payroll+mk+qi+rd+ci+ethics;const profit=revenue-variable-op-interest;b.inventory-=sold;b.revenue+=revenue;b.expenses+=Math.max(0,variable+op+interest);b.lastProfit=profit;b.cash+=profit;b.customers=Math.max(0,Math.round(b.customers*(1-b.churn/100)+sold*.45));b.churn=clamp(5+Math.max(0,60-b.satisfaction)*.12+Math.max(0,55-b.reputation)*.06-b.product.quality*.015);b.satisfaction=clamp(b.satisfaction+(b.product.quality-65)*.02+(coverage-.9)*5-b.churn*.03);b.share=clamp(b.share+(sold/Math.max(1,baseDemand))*.8-pressure*.5);b.valuation=valuation(b,w.macro,w.industry);b.stage=stage(b);
 for(const s of w.segments){const m=w.memory[s.id];w.memory[s.id]={price:clamp(m.price*.95+b.product.price*.05),quality:clamp(m.quality*.92+b.product.quality*.08),service:clamp(m.service*.92+b.product.service*.08),delivery:clamp(m.delivery*.92+b.product.delivery*.08),trust:clamp(m.trust*.94+b.reputation*.06),loyalty:clamp(m.loyalty+(sold>0?.4:-.15)),purchases:m.purchases+Math.min(1,sold/Math.max(1,baseDemand))}}
 w.competitors=w.competitors.map(c=>competitorStep(c,b,w.macro));const investorSuccess=profit>0&&b.valuation>=w.business.valuation;w.investors=w.investors.map(x=>({...x,relationship:clamp(x.relationship+(investorSuccess&&x.risk>=45?.8:-.5))}));
 e.push({source:"macro.interestRate",target:"financing",magnitude:w.macro.interestRate-input.macro.interestRate,explanation:"interest rates change debt service and capital availability"},{source:"price",target:"demand",magnitude:b.product.price-oldPrice,explanation:"segment-specific price elasticity changes demand"},{source:"workforce",target:"capacity",magnitude:b.employees-input.business.employees,explanation:"labor skills and morale determine effective capacity"},{source:"supply",target:"inventory",magnitude:coverage,explanation:"supplier capacity constrains production"},{source:"customers",target:"reputation",magnitude:b.satisfaction-input.business.satisfaction,explanation:"experience feeds trust, retention and reputation"});w.business=b;w.effects=[...w.effects,...e].slice(-100);report.push(`Day ${w.day}: demand ${baseDemand.toFixed(1)}, sold ${sold.toFixed(1)}, revenue ${revenue.toFixed(0)}, profit ${profit.toFixed(0)}.`);report.push(`Macro: growth ${w.macro.growth.toFixed(1)}%, inflation ${w.macro.inflation.toFixed(1)}%, rate ${w.macro.interestRate.toFixed(1)}%.`);report.push(`Business: ${b.stage}, cash ${b.cash.toFixed(0)}, reputation ${b.reputation.toFixed(0)}, share ${b.share.toFixed(2)}%, valuation ${b.valuation.toFixed(0)}.`);return{state:w,effects:e,report}
}

export function validateWorld(w:World):string[]{const x:string[]=[];const finite=(n:string,v:number)=>{if(!Number.isFinite(v))x.push(`${n} is not finite`)};finite("cash",w.business.cash);finite("revenue",w.business.revenue);finite("debt",w.business.debt);finite("day",w.day);if(w.day<1)x.push("day must be positive");if(w.business.cash<0)x.push("cash cannot be negative");if(w.business.debt<0)x.push("debt cannot be negative");if(w.business.inventory<0)x.push("inventory cannot be negative");if(w.business.share<0||w.business.share>100)x.push("share out of bounds");if(w.business.reputation<0||w.business.reputation>100)x.push("reputation out of bounds");if(w.business.product.price<=0)x.push("price must be positive");return x}
export function runLong(world:World,days:number,rng:Rng):World{let w=world;for(let i=0;i<days;i++){if(w.business.stage==="failure")break;w=stepWorld(w,{},rng).state;const errors=validateWorld(w);if(errors.length)throw new Error(errors.join("; "))}return w}
export function runMonteCarlo(runs:number,days:number,seed:number,industry:IndustryId="technology"){let survivors=0,valuation=0,profit=0;for(let i=0;i<Math.max(1,runs);i++){const rng=createRng((seed+i*2654435761)>>>0);let w=createWorld((seed+i)>>>0,industry);w=runLong(w,days,rng);if(w.business.stage!=="failure")survivors++;valuation+=w.business.valuation;profit+=w.business.lastProfit}const n=Math.max(1,runs);return{survivalRate:survivors/n,meanValuation:valuation/n,meanProfit:profit/n}}
