import type { Business, BusinessStructure, CharacterMemory, Customer, EconomyState, Product, SimulationChoice, SimulationEvent, SimulationState, Supplier } from "@enterpriseverse/types";
import { defaultOperations } from "./operations";
import { advanceMarket, createMarketState, explainMarketPosition } from "./market";
import { createCompetitorAgents, createCustomerAgents, createInvestorAgents, createSupplierAgents, decideCompetitorMove, decideCustomerPurchase, evaluateInvestment, negotiateSupplier } from "./agents";
import { advanceEconomyDay, createEconomyState, createProduct } from "./economy";
import { getLifecycleStage } from "./lifecycle";
import { createWorkforce, advanceWorkforce } from "./workforce";
import { calculateFinancialSnapshot } from "./finance";
import { advanceConsequences, consequenceFromChoice, createConsequenceState, scheduleConsequence } from "./consequences";
import { advanceScenarios, createScenarioState } from "./scenarios";
import { createReplayState, recordDecision, recordSnapshot } from "./replay";
import { assessRun, scoreDecisionOutcome } from "./assessment";
import { assertSimulationState, buildDynamicEvent, resolvePhase1Consequences, schedulePhase1Consequences } from "./phase1";

export { createCustomerAgents, createSupplierAgents, createCompetitorAgents, createInvestorAgents, decideCustomerPurchase, negotiateSupplier, decideCompetitorMove, evaluateInvestment } from "./agents";
export { applyBusinessAction, calculateKpis, defaultOperations } from "./operations";
export { advanceMarket, createMarketState, explainMarketPosition } from "./market";
export { calculateIntegratedMetrics, validateIntegratedState } from "./integration";
export { assessLearning, scoreDecisionOutcome as scoreLearningDecision } from "./learning";
export * from "./economy";
export * from "./lifecycle";
export * from "./workforce";
export * from "./finance";
export * from "./consequences";
export * from "./scenarios";
export * from "./replay";
export * from "./assessment";
export * from "./phase4";
export * from "./phase7";
export * from "./phase1";
export * from "./phase3";
