import { advancePhase3World, createPhase3World, type Phase3Decision, type Phase3Event, type Phase3Industry, type Phase3World } from './phase3';

export type DeepStrategy='low_price'|'premium'|'growth'|'marketing'|'research'|'conservative';export type DeepHorizon='today'|'week'|'month'|'long_term';
export interface DeepPlan{strategy:DeepStrategy;horizon:DeepHorizon;priceTarget:number;capacityTarget:number;inventoryTarget:number;cashBuffer:number;riskBudget:number}
export interface DeepRegulation{taxRate:number;qualityStandard:number;laborStandard:number;environmentalPressure:number;complianceBudget:number}
export interface DeepCustomerMemory{price:number;quality:number;service:number;delivery:number;trust:number;lastDay:number}
export interface DeepCustomerAgent{id:string;segment:string;income:number;priceSensitivity:number;qualitySensitivity:number;brandSensitivity:number;switchingCost:number;memory:DeepCustomerMemory;stage:'awareness'|'consideration'|'acquired'|'repeat'|'loyal'|'advocate'|'churned'}
export interface DeepSupplierAgent{id:string;capacity:number;available:number;unitCost:number;reliability:number;quality:number;leadTime:number;relationship:number;paymentTrust:number;priority:number}
export interface DeepCompetitorAgent{id:string;strategy:'cost_leader'|'premium_specialist'|'fast_follower'|'innovator'|'aggressive_entrant'|'conservative_incumbent';cash:number;capacity:number;price:number;quality:number;marketing:number;belief:number;lastDecision:string}
export interface DeepInvestorAgent{id:string;riskTolerance:number;growthPreference:number;profitPreference:number;patience:number;capital:number;decision:'invest'|'wait'|'reject'}
export interface DeepWorkforce{headcount:number;skillPool:number;morale:number;workload:number;productivity:number;turnoverRisk:number;hiringPool:number;trainingHours:number;wageIndex:number}
export interface DeepFinance{cash:number;debt:number;interest:number;revenue:number;operatingCost:number;capex:number;freeCashFlow:number;valuation:number;creditScore:number}
export interface DeepProduction{capacity:number;equipment:number;materials:number;output:number;yield:number;waste:number;unitCost:number;warehouse:number}
export interface DeepMarket{addressableDemand:number;servedDemand:number;industryGrowth:number;seasonality:number;priceIndex:number;competitivePressure:number}
export interface DeepCrisis{kind:'cash'|'supply'|'workforce'|'reputation'|'market'|'debt';severity:number;started:number;expires:number;causes:string[]}
export interface DeepTrace{day:number;decision:Phase3Decision;cause:string;effect:string;magnitude:number;delay:number;entity:string}
export interface DeepWorld extends Phase3World{deep:{plan:DeepPlan;regulation:DeepRegulation;customers:DeepCustomerAgent[];suppliers:DeepSupplierAgent[];competitors:DeepCompetitorAgent[];investors:DeepInvestorAgent[];workforce:DeepWorkforce;finance:DeepFinance;production:DeepProduction;market:DeepMarket;crises:DeepCrisis[];traces:DeepTrace[];pending:DeepTrace[];version:1}}

const c=(v:number,min=0,max=1)=>Number.isFinite(v)?Math.min(max,Math.max(min,v)):min;const h=(seed:number,day:number,key:string)=>{let x=(seed^day)>>>0;for(let i=0;i<key.length;i++)x=Math.imul(x^key.charCodeAt(i),16777619)>>>0;return x/4294967296};const clone=<T>(x:T):T=>JSON.parse(JSON.stringify(x)) as T;

function makeDeep(base:Phase3World):DeepWorld{const seg=base.segments;return Object.assign(base,{deep:{version:1,plan:{strategy:'conservative',horizon:'week',priceTarget:100,capacityTarget:base.production.capacity,inventoryTarget:base.inventory.finishedGoods,cashBuffer:5000,riskBudget:.2},regulation:{taxRate:.2,qualityStandard:60,laborStandard:50,environmentalPressure:base.regulation.pressure,complianceBudget:base.regulation.complianceCost},customers:base.customers.map((x,i)=>{const s=seg.find(v=>v.id===x.segment);return{id:x.id,segment:x.segment,income:800+(i*137)%1200,priceSensitivity:s?.priceSensitivity??1,qualitySensitivity:s?.qualitySensitivity??1,brandSensitivity:s?.brandSensitivity??1,switchingCost:s?.switchingCost??.2,memory:{price:x.priceMemory,quality:x.qualityMemory,service:x.serviceMemory,delivery:70,trust:x.trust,lastDay:x.lastPurchaseDay},stage:x.stage}}),suppliers:base.suppliers.map(x=>({id:x.id,capacity:x.capacity,available:x.availableCapacity,unitCost:x.unitCost,reliability:x.reliability,quality:x.quality,leadTime:x.leadTime,relationship:x.relationship,paymentTrust:x.financialHealth,priority:x.relationship})),competitors:base.competitors.map(x=>({id:x.id,strategy:x.strategy,cash:x.cash,capacity:120,price:x.price,quality:x.quality,marketing:x.marketing,belief:x.perceptionAccuracy,lastDecision:x.lastAction})),investors:[{id:'investor-1',riskTolerance:.45,growthPreference:.65,profitPreference:.55,patience:.7,capital:50000,decision:'wait'},{id:'investor-2',riskTolerance:.7,growthPreference:.8,profitPreference:.35,patience:.45,capital:100000,decision:'wait'}],workforce:{headcount:base.workforce.headcount,skillPool:base.workforce.skills,morale:base.workforce.morale,workload:base.workforce.workload,productivity:base.workforce.productivity,turnoverRisk:100-base.workforce.retention,hiringPool:c(base.macro.unemployment/20)*100,trainingHours:base.workforce.training,wageIndex:100+base.workforce.wagePressure},finance:{cash:base.finance.cash,debt:base.capital.debt,interest:base.macro.interestRate,revenue:base.finance.revenue,operatingCost:base.finance.costs,capex:base.finance.capex,freeCashFlow:base.finance.netCashFlow,valuation:base.finance.valuation,creditScore:base.capital.creditScore},production:{capacity:base.production.capacity,equipment:base.production.equipmentCondition,materials:base.inventory.rawMaterials,output:base.production.output,yield:base.production.qualityYield,waste:base.inventory.waste,unitCost:base.production.unitCost,warehouse:base.inventory.warehouseCapacity},market:{addressableDemand:base.markets[0].size,servedDemand:base.markets[0].demandIndex,industryGrowth:base.macro.growthRate,seasonality:0,priceIndex:base.markets[0].averagePrice,competitivePressure:base.industries.find(i=>i.id===base.markets[0].industry)?.competitionIntensity??.5},crises:[],traces:[],pending:[]}})}

export function createDeepPhase3World(seed=1,industry:Phase3Industry='retail'):DeepWorld{return makeDeep(createPhase3World(seed,industry))}
export function setDeepStrategy(world:DeepWorld,plan:Partial<DeepPlan>):DeepWorld{const w=clone(world);w.deep.plan={...w.deep.plan,...plan};return w}
export function scheduleDeepEffect(world:DeepWorld,trace:DeepTrace):DeepWorld{const w=clone(world);w.deep.pending.push(trace);w.deep.pending.sort((a,b)=>a.day-b.day);return w}
export function marketIntelligence(world:DeepWorld){return{day:world.day,trend:world.markets[0].trend,demandIndex:world.markets[0].demandIndex,price:world.markets[0].averagePrice,competitorPrices:world.deep.competitors.map(x=>x.price),competitorQuality:world.deep.competitors.map(x=>x.quality),supplierTightness:1-world.deep.production.materials/Math.max(1,world.deep.production.capacity),customerSentiment:world.information.customerSentiment,economic:clone(world.macro),confidence:world.information.confidence}}
function applyDelayed(w:DeepWorld){const due=w.deep.pending.filter(x=>x.day<=w.day);w.deep.pending=w.deep.pending.filter(x=>x.day>w.day);w.deep.traces.push(...due)}
function eventOverlay(w:DeepWorld):Phase3Event[]{const e=[...w.events];if(w.deep.finance.cash<w.deep.plan.cashBuffer)e.push({id:`cash-crisis-${w.day}`,day:w.day,kind:'cash_crisis',severity:c((w.deep.plan.cashBuffer-w.deep.finance.cash)/Math.max(1,w.deep.plan.cashBuffer)),duration:3,source:'finance',effects:{investment:-.2,demand:-.02},expiresDay:w.day+3});if(w.deep.production.materials<w.deep.production.capacity*.15)e.push({id:`material-crisis-${w.day}`,day:w.day,kind:'material_shortage',severity:c(1-w.deep.production.materials/Math.max(1,w.deep.production.capacity*.15)),duration:3,source:'supply',effects:{supplierCapacity:-.25},expiresDay:w.day+3});if(w.deep.workforce.turnoverRisk>65)e.push({id:`workforce-crisis-${w.day}`,day:w.day,kind:'workforce_crisis',severity:c((w.deep.workforce.turnoverRisk-65)/35),duration:4,source:'workforce',effects:{capacity:-.15,quality:-.03},expiresDay:w.day+4});if(w.reputation.trust<35)e.push({id:`reputation-crisis-${w.day}`,day:w.day,kind:'reputation_crisis',severity:c((35-w.reputation.trust)/35),duration:5,source:'reputation',effects:{demand:-.08},expiresDay:w.day+5});return e}

export function advanceDeepPhase3World(previous:DeepWorld,decision:Phase3Decision={}):DeepWorld{const prior=clone(previous.deep);applyDelayed(previous);const base=advancePhase3World(previous,decision);const w=makeDeep(base);w.deep.plan=prior.plan;w.deep.regulation=prior.regulation;w.deep.customers=prior.customers;w.deep.suppliers=prior.suppliers;w.deep.competitors=prior.competitors;w.deep.investors=prior.investors;w.deep.crises=prior.crises.filter(x=>x.expires>=w.day);w.deep.traces=prior.traces.slice(-1000);w.deep.pending=prior.pending.slice(-500);w.deep.finance={cash:w.finance.cash,debt:w.capital.debt,interest:w.macro.interestRate,revenue:w.finance.revenue,operatingCost:w.finance.costs,capex:w.finance.capex,freeCashFlow:w.finance.netCashFlow,valuation:w.finance.valuation,creditScore:w.capital.creditScore};w.deep.production={capacity:w.production.capacity,equipment:w.production.equipmentCondition,materials:w.inventory.rawMaterials,output:w.production.output,yield:w.production.qualityYield,waste:w.inventory.waste,unitCost:w.production.unitCost,warehouse:w.inventory.warehouseCapacity};w.deep.market={addressableDemand:w.markets[0].size,servedDemand:w.markets[0].demandIndex,industryGrowth:w.macro.growthRate,seasonality:Math.sin(w.day/30)*.08,priceIndex:w.markets[0].averagePrice,competitivePressure:w.industries.find(i=>i.id===w.markets[0].industry)?.competitionIntensity??.5};
 const price=w.markets[0].averagePrice;for(const customer of w.deep.customers){const m=customer.memory;const utility=-(price-m.price)/Math.max(1,m.price)*customer.priceSensitivity+(w.reputation.productQuality-m.quality)/100*customer.qualitySensitivity+(w.reputation.trust-m.trust)/100*customer.brandSensitivity+(w.reputation.service-m.service)/200;const buy=c(.18+utility*.2+customer.switchingCost*.03);if(h(w.seed,w.day,customer.id)<buy){customer.memory={price,quality:w.reputation.productQuality,service:w.reputation.service,delivery:w.reputation.reliability,trust:w.reputation.trust,lastDay:w.day};customer.stage=customer.stage==='awareness'?'acquired':customer.stage==='acquired'?'repeat':customer.stage==='repeat'?'loyal':customer.stage==='loyal'?'advocate':customer.stage}}
 const tight=1-w.deep.production.materials/Math.max(1,w.deep.production.capacity);for(const s of w.deep.suppliers){s.available=c(s.available/Math.max(1,s.capacity))*s.capacity;s.relationship=c(s.relationship/100)*100;s.paymentTrust=c(s.paymentTrust/100)*100;if(tight>.6)s.unitCost*=1+.02*tight;if(w.deep.finance.cash<w.deep.plan.cashBuffer)s.paymentTrust=c(s.paymentTrust/100-.01)*100;s.priority=c((s.relationship*.5+s.reliability*.35+s.quality*.15)/100)*100}
 const pressure=w.markets[0].demandIndex/100;for(const comp of w.deep.competitors){const observed=comp.price+(price-comp.price)*comp.belief;const gain=pressure-.9;switch(comp.strategy){case'cost_leader':comp.price=c(observed*.985,.3,200);break;case'premium_specialist':comp.quality=c(comp.quality/100+.01*gain)*100;break;case'fast_follower':comp.price=observed;break;case'innovator':comp.quality=c(comp.quality/100+.015)*100;comp.capacity=Math.min(100000,comp.capacity+2);break;case'aggressive_entrant':comp.price=Math.max(30,observed-3*gain);comp.capacity=Math.min(100000,comp.capacity+Math.max(0,gain)*4);break;default:comp.price=comp.price*.995+observed*.005}}
 const turnover=c((w.deep.workforce.workload-65)/35)*.2+c((60-w.deep.workforce.morale)/60)*.15;w.deep.workforce.turnoverRisk=c(turnover)*100;w.deep.workforce.hiringPool=c(w.macro.unemployment/20)*100;w.deep.workforce.skillPool=w.workforce.skills;w.deep.workforce.trainingHours+=Math.max(0,decision.training??0);w.deep.workforce.wageIndex=100+w.workforce.wagePressure;
 for(const investor of w.deep.investors){const growth=w.macro.growthRate/8;const profit=w.finance.netCashFlow/Math.max(1,w.finance.revenue);const risk=c(w.capital.debt/Math.max(1,w.finance.revenue));const score=growth*investor.growthPreference+profit*investor.profitPreference-risk*(1-investor.riskTolerance);investor.decision=score>.08&&w.capital.investorConfidence>50?'invest':score>-.02?'wait':'reject';if(investor.decision==='invest'&&investor.capital>0){const funding=Math.min(1000,investor.capital);investor.capital-=funding;w.finance.cash=Math.min(1e12,w.finance.cash+funding);w.capital.availableCapital=Math.min(200000,w.capital.availableCapital+funding)}}
 const events=eventOverlay(w);w.events=events;for(const e of events){if(e.kind==='cash_crisis'&&e.severity>.5)w.deep.crises.push({kind:'cash',severity:e.severity,started:w.day,expires:e.expiresDay,causes:['cash below buffer','financing pressure']});if(e.kind==='material_shortage'&&e.severity>.5)w.deep.crises.push({kind:'supply',severity:e.severity,started:w.day,expires:e.expiresDay,causes:['low materials','capacity constraint']});if(e.kind==='workforce_crisis'&&e.severity>.5)w.deep.crises.push({kind:'workforce',severity:e.severity,started:w.day,expires:e.expiresDay,causes:['workload','morale','turnover risk']});if(e.kind==='reputation_crisis'&&e.severity>.5)w.deep.crises.push({kind:'reputation',severity:e.severity,started:w.day,expires:e.expiresDay,causes:['trust below threshold']})}
 const tax=Math.max(0,(w.finance.grossProfit-w.finance.interestExpense))*w.deep.regulation.taxRate;w.finance.cash=clamp(w.finance.cash-tax,0,1e12);w.deep.finance.cash=w.finance.cash;w.deep.finance.freeCashFlow=w.finance.netCashFlow-tax;w.regulation.violationRisk=c((w.deep.regulation.qualityStandard-w.reputation.productQuality)/100);if(w.workforce.morale<w.deep.regulation.laborStandard)w.regulation.violationRisk=c(w.regulation.violationRisk+.05);const trace={day:w.day,decision,cause:'macro, market, customer, supply, workforce and capital conditions',effect:'business outcome',magnitude:w.finance.netCashFlow-tax,delay:0,entity:'business'};w.deep.traces.push(trace);w.telemetry.push({day:w.day,decision:JSON.stringify(decision),causes:['economy','market','supply','customers','workforce','competition','capital'],effects:['demand','production','cash','reputation','valuation'],entity:'deep-world',version:1,seed:w.seed});return w}

export interface DeepValidationReport{errors:string[];warnings:string[]}
export function validateDeepPhase3World(w:DeepWorld):DeepValidationReport{const errors:string[]=[];const warnings:string[]=[];const finite=[w.deep.finance.cash,w.deep.finance.debt,w.deep.finance.revenue,w.deep.finance.valuation,w.deep.production.capacity,w.deep.production.output,w.deep.production.materials,w.deep.workforce.headcount,w.deep.workforce.morale,w.deep.workforce.productivity];if(finite.some(x=>!Number.isFinite(x)))errors.push('non-finite deep state');if(w.deep.finance.debt<0||w.deep.production.materials<0||w.deep.production.output<0)errors.push('negative conserved state');if(w.deep.production.output>w.deep.production.capacity+1e-9)errors.push('production exceeds capacity');if(w.deep.workforce.headcount<1)errors.push('invalid workforce');if(w.deep.competitors.some(x=>x.price<0||x.quality<0||x.quality>100))errors.push('invalid competitor state');if(w.deep.customers.some(x=>x.memory.quality<0||x.memory.quality>100))errors.push('invalid customer memory');if(w.deep.suppliers.some(x=>x.available<0||x.available>x.capacity+1e-9))errors.push('supplier capacity violation');if(w.deep.finance.cash<w.deep.plan.cashBuffer)warnings.push('cash below strategic buffer');return{errors,warnings}}
export function runDeepPhase3(initial:DeepWorld,days:number,decisions:Phase3Decision[]=[]):DeepWorld[]{const result=[clone(initial)];let w=initial;for(let i=0;i<days;i++){w=advanceDeepPhase3World(w,decisions[i]??{});const r=validateDeepPhase3World(w);if(r.errors.length)throw new Error(r.errors.join('; '));result.push(clone(w))}return result}
export function counterfactualDeepPhase3(world:DeepWorld,decision:Phase3Decision,days=30){return runDeepPhase3(clone(world),days,Array.from({length:days},()=>decision))[days]}
export function runDeepMonteCarlo(runs=100,days=365){const outcomes:Array<{seed:number;cash:number;valuation:number;survived:boolean}>=[];for(let seed=1;seed<=runs;seed++){const w=runDeepPhase3(createDeepPhase3World(seed),days)[days];outcomes.push({seed,cash:w.finance.cash,valuation:w.finance.valuation,survived:w.lifecycle!=='failed'})}const survived=outcomes.filter(x=>x.survived).length;return{runs,days,survivalRate:survived/runs,averageCash:outcomes.reduce((a,x)=>a+x.cash,0)/runs,averageValuation:outcomes.reduce((a,x)=>a+x.valuation,0)/runs,minCash:Math.min(...outcomes.map(x=>x.cash)),maxCash:Math.max(...outcomes.map(x=>x.cash))}}
export function runDeepAdversarialSuite(seed=1){const cases:Phase3Decision[]=[{price:1e99},{price:0},{borrowing:1e99},{repayment:1e99},{hiring:1e99},{layoffs:1e99},{marketing:1e99},{capacityInvestment:1e99},{productionTarget:1e99},{training:1e99}];const failures:string[]=[];for(const d of cases)try{const w=runDeepPhase3(createDeepPhase3World(seed),30,Array.from({length:30},()=>d))[30];const r=validateDeepPhase3World(w);if(r.errors.length)failures.push(r.errors.join('; '))}catch(e){failures.push(e instanceof Error?e.message:'unknown failure')}return{cases:cases.length,failures,passed:failures.length===0}}
export function deepStrategyDiversity(seed=1,days=180){const plans:Record<DeepStrategy,Phase3Decision>={low_price:{price:75,marketing:5},premium:{price:125,qualityInvestment:25,marketing:10},growth:{price:105,hiring:3,capacityInvestment:1000,borrowing:5000},marketing:{price:100,marketing:50},research:{price:105,research:40,qualityInvestment:20},conservative:{price:100,repayment:100}};return Object.entries(plans).map(([strategy,d])=>{const w=runDeepPhase3(createDeepPhase3World(seed),days,Array.from({length:days},()=>d))[days];return{strategy,cash:w.finance.cash,revenue:w.finance.revenue,valuation:w.finance.valuation,marketShare:w.markets[0].marketShare,crises:w.deep.crises.length}})}
