import type { SimulationState } from '@enterpriseverse/types';

export type Phase3Industry = 'technology'|'retail'|'manufacturing'|'food'|'services'|'logistics';
export type Phase3Trend = 'growing'|'stable'|'declining';
export type Phase3CompetitorStrategy = 'cost_leader'|'premium_specialist'|'fast_follower'|'innovator'|'aggressive_entrant'|'conservative_incumbent';
export type Phase3CustomerSegment = 'budget'|'mainstream'|'premium'|'enterprise';
export type Phase3Lifecycle = 'idea'|'launch'|'validation'|'survival'|'growth'|'scale'|'maturity'|'crisis'|'failed';

export interface Phase3MacroEconomy {day:number;inflation:number;interestRate:number;growthRate:number;unemployment:number;consumerConfidence:number;businessConfidence:number;creditAvailability:number;commodityIndex:number;}
export interface Phase3IndustryState {id:Phase3Industry;capitalIntensity:number;laborIntensity:number;baseMargin:number;demandElasticity:number;competitionIntensity:number;growthRate:number;supplierConcentration:number;regulatoryPressure:number;}
export interface Phase3MarketState {id:string;industry:Phase3Industry;size:number;trend:Phase3Trend;trendStrength:number;averagePrice:number;demandIndex:number;marketShare:number;}
export interface Phase3CustomerSegmentState {id:Phase3CustomerSegment;population:number;priceSensitivity:number;qualitySensitivity:number;brandSensitivity:number;switchingCost:number;loyalty:number;purchaseFrequency:number;incomeSensitivity:number;}
export interface Phase3CustomerState {id:string;segment:Phase3CustomerSegment;awareness:number;consideration:number;satisfaction:number;loyalty:number;trust:number;priceMemory:number;qualityMemory:number;serviceMemory:number;churnRisk:number;purchases:number;stage:'awareness'|'consideration'|'acquired'|'repeat'|'loyal'|'advocate'|'churned';lastPurchaseDay:number;}
export interface Phase3SupplierState {id:string;capacity:number;availableCapacity:number;unitCost:number;quality:number;reliability:number;leadTime:number;relationship:number;financialHealth:number;paymentTerms:number;}
export interface Phase3WorkforceState {headcount:number;skills:number;morale:number;workload:number;productivity:number;retention:number;wagePressure:number;hiringDifficulty:number;training:number;}
export interface Phase3CompetitorState {id:string;strategy:Phase3CompetitorStrategy;cash:number;marketShare:number;price:number;quality:number;marketing:number;riskTolerance:number;capitalAccess:number;timeHorizon:number;aggression:number;perceptionAccuracy:number;lastAction:string;}
export interface Phase3CapitalState {creditScore:number;debt:number;interestRate:number;creditLimit:number;investorConfidence:number;availableCapital:number;equityValue:number;}
export interface Phase3FinanceState {cash:number;revenue:number;costs:number;grossProfit:number;netCashFlow:number;debt:number;interestExpense:number;valuation:number;inventoryValue:number;capex:number;}
export interface Phase3ReputationState {trust:number;productQuality:number;service:number;reliability:number;ethics:number;employeeTreatment:number;}
export interface Phase3InventoryState {rawMaterials:number;finishedGoods:number;warehouseCapacity:number;waste:number;turnover:number;}
export interface Phase3ProductionState {capacity:number;output:number;utilization:number;unitCost:number;leadTime:number;qualityYield:number;equipmentCondition:number;}
export interface Phase3RegulationState {pressure:number;complianceCost:number;violationRisk:number;}
export interface Phase3InvestorState {riskTolerance:number;growthPreference:number;profitPreference:number;patience:number;capitalAvailable:number;lastDecision:'invest'|'wait'|'reject';}
export interface Phase3Event {id:string;day:number;kind:string;severity:number;duration:number;source:string;effects:Record<string,number>;expiresDay:number;}
export interface Phase3CausalEffect {cause:string;effect:string;magnitude:number;entity:string;}
export interface Phase3Explainability {day:number;outcome:string;effects:Phase3CausalEffect[];}
export interface Phase3Telemetry {day:number;decision:string;causes:string[];effects:string[];entity:string;version:1;seed:number;}
export interface Phase3Information {marketTrend:number;competitorSignals:number[];customerSentiment:number;supplierTightness:number;economicIndicators:Phase3MacroEconomy;confidence:number;}
export interface Phase3World {version:1;seed:number;day:number;macro:Phase3MacroEconomy;industries:Phase3IndustryState[];markets:Phase3MarketState[];customers:Phase3CustomerState[];segments:Phase3CustomerSegmentState[];suppliers:Phase3SupplierState[];workforce:Phase3WorkforceState;competitors:Phase3CompetitorState[];capital:Phase3CapitalState;finance:Phase3FinanceState;reputation:Phase3ReputationState;inventory:Phase3InventoryState;production:Phase3ProductionState;regulation:Phase3RegulationState;investor:Phase3InvestorState;lifecycle:Phase3Lifecycle;events:Phase3Event[];explanations:Phase3Explainability[];telemetry:Phase3Telemetry[];information:Phase3Information;}

const INDUSTRIES:Phase3IndustryState[]=[
{id:'technology',capitalIntensity:.55,laborIntensity:.65,baseMargin:.22,demandElasticity:1.25,competitionIntensity:.75,growthRate:.045,supplierConcentration:.35,regulatoryPressure:.3},
{id:'retail',capitalIntensity:.4,laborIntensity:.7,baseMargin:.1,demandElasticity:1.55,competitionIntensity:.85,growthRate:.02,supplierConcentration:.45,regulatoryPressure:.35},
{id:'manufacturing',capitalIntensity:.85,laborIntensity:.55,baseMargin:.14,demandElasticity:1.1,competitionIntensity:.65,growthRate:.025,supplierConcentration:.6,regulatoryPressure:.55},
{id:'food',capitalIntensity:.45,laborIntensity:.75,baseMargin:.12,demandElasticity:1.35,competitionIntensity:.8,growthRate:.018,supplierConcentration:.5,regulatoryPressure:.5},
{id:'services',capitalIntensity:.25,laborIntensity:.9,baseMargin:.18,demandElasticity:1.2,competitionIntensity:.7,growthRate:.03,supplierConcentration:.2,regulatoryPressure:.2},
{id:'logistics',capitalIntensity:.8,laborIntensity:.65,baseMargin:.11,demandElasticity:1.05,competitionIntensity:.7,growthRate:.035,supplierConcentration:.4,regulatoryPressure:.45}];
const SEGMENTS:Phase3CustomerSegmentState[]=[
{id:'budget',population:35,priceSensitivity:1.45,qualitySensitivity:.55,brandSensitivity:.45,switchingCost:.1,loyalty:.35,purchaseFrequency:.7,incomeSensitivity:1.1},
{id:'mainstream',population:40,priceSensitivity:1,qualitySensitivity:1,brandSensitivity:.8,switchingCost:.25,loyalty:.5,purchaseFrequency:1,incomeSensitivity:.8},
{id:'premium',population:18,priceSensitivity:.55,qualitySensitivity:1.35,brandSensitivity:1.3,switchingCost:.35,loyalty:.65,purchaseFrequency:.8,incomeSensitivity:.65},
{id:'enterprise',population:7,priceSensitivity:.45,qualitySensitivity:1.45,brandSensitivity:1.1,switchingCost:.7,loyalty:.72,purchaseFrequency:.55,incomeSensitivity:.5}];
const strategies:Phase3CompetitorStrategy[]=['cost_leader','premium_specialist','fast_follower','innovator'];
const clamp=(v:number,min:number,max:number)=>Number.isFinite(v)?Math.min(max,Math.max(min,v)):min;
const b=(v:number)=>clamp(v,0,1);
const hash=(seed:number,day:number,key:string)=>{let h=(seed^day)>>>0;for(let i=0;i<key.length;i++)h=Math.imul(h^key.charCodeAt(i),16777619)>>>0;return(h>>>0)/4294967296;};
const shock=(w:Phase3World,key:string,a=.02)=>(hash(w.seed,w.day,key)-.5)*2*a;
const copy=<T>(v:T):T=>JSON.parse(JSON.stringify(v)) as T;

export function createPhase3World(seed=1,industry:Phase3Industry='retail'):Phase3World{
 const competitors=strategies.map((strategy,i)=>({id:`competitor-${i+1}`,strategy,cash:50000+i*15000,marketShare:[.18,.14,.12,.1][i],price:100,quality:70+i*6,marketing:20,riskTolerance:.25+i*.15,capitalAccess:.45+i*.1,timeHorizon:.5+i*.08,aggression:.3+i*.12,perceptionAccuracy:.8,lastAction:'hold'}));
 const customers=Array.from({length:40},(_,i)=>{const s=SEGMENTS[i%4];return{id:`customer-${i+1}`,segment:s.id,awareness:40,consideration:35,satisfaction:70,loyalty:s.loyalty*100,trust:60,priceMemory:100,qualityMemory:70,serviceMemory:70,churnRisk:15,purchases:0,stage:'awareness' as const,lastPurchaseDay:0};});
 const suppliers=Array.from({length:4},(_,i)=>({id:`supplier-${i+1}`,capacity:100+i*35,availableCapacity:100+i*35,unitCost:55+i*3,quality:72+i*5,reliability:70+i*6,leadTime:2+i,relationship:50,financialHealth:75,paymentTerms:30}));
 return{version:1,seed,day:1,macro:{day:1,inflation:3,interestRate:6,growthRate:2.5,unemployment:5,consumerConfidence:65,businessConfidence:65,creditAvailability:70,commodityIndex:100},industries:INDUSTRIES.map(copy),markets:[{id:'primary',industry,size:100000,trend:'stable',trendStrength:0,averagePrice:100,demandIndex:100,marketShare:.1}],customers,segments:SEGMENTS.map(copy),suppliers,workforce:{headcount:10,skills:70,morale:72,workload:55,productivity:70,retention:85,wagePressure:3,hiringDifficulty:30,training:0},competitors,capital:{creditScore:70,debt:0,interestRate:6,creditLimit:50000,investorConfidence:60,availableCapital:20000,equityValue:50000},finance:{cash:20000,revenue:0,costs:0,grossProfit:0,netCashFlow:0,debt:0,interestExpense:0,valuation:50000,inventoryValue:5000,capex:0},reputation:{trust:50,productQuality:70,service:70,reliability:70,ethics:70,employeeTreatment:70},inventory:{rawMaterials:500,finishedGoods:150,warehouseCapacity:2000,waste:0,turnover:0},production:{capacity:120,output:0,utilization:0,unitCost:55,leadTime:2,qualityYield:.95,equipmentCondition:90},regulation:{pressure:INDUSTRIES.find(x=>x.id===industry)?.regulatoryPressure??.35,complianceCost:200,violationRisk:.02},investor:{riskTolerance:.5,growthPreference:.6,profitPreference:.5,patience:.65,capitalAvailable:50000,lastDecision:'wait'},lifecycle:'launch',events:[],explanations:[],telemetry:[],information:{marketTrend:0,competitorSignals:[],customerSentiment:70,supplierTightness:0,economicIndicators:{day:1,inflation:3,interestRate:6,growthRate:2.5,unemployment:5,consumerConfidence:65,businessConfidence:65,creditAvailability:70,commodityIndex:100},confidence:.7}};
}

export interface Phase3Decision {price?:number;qualityInvestment?:number;marketing?:number;hiring?:number;training?:number;capacityInvestment?:number;inventoryTarget?:number;borrowing?:number;repayment?:number;research?:number;ethics?:number;service?:number;productionTarget?:number;layoffs?:number;marketExpansion?:number;diversify?:number;strategy?:'premium'|'low_cost'|'growth'|'conservative'|'marketing'|'research';}

function updateMacro(w:Phase3World,d:Phase3Decision){const m=w.macro;const inf=clamp(m.inflation+(m.commodityIndex-100)*.008+shock(w,'inf',.12),0,20);const rate=clamp(m.interestRate+(inf-3)*.09-(m.growthRate-2.5)*.05,0,18);const growth=clamp(m.growthRate+(m.consumerConfidence-60)*.012-(rate-6)*.07+shock(w,'growth',.1),-8,8);const unemp=clamp(m.unemployment-(growth-2.5)*.08+shock(w,'unemp',.08),2,20);return{day:w.day,inflation:inf,interestRate:rate,growthRate:growth,unemployment:unemp,consumerConfidence:clamp(m.consumerConfidence+(growth-2.5)*.7-(inf-3)*.45,10,95),businessConfidence:clamp(m.businessConfidence+(growth-2.5)*.6-(rate-6)*.3,10,95),creditAvailability:clamp(m.creditAvailability-(rate-6)*.7-(w.capital.debt/100000)*6,10,95),commodityIndex:clamp(m.commodityIndex+(inf-3)*.35+shock(w,'commodity',.45),70,160)};}

function events(w:Phase3World):Phase3Event[]{const e:Phase3Event[]=[];const m=w.macro;if(m.inflation>8)e.push({id:`inflation-${w.day}`,day:w.day,kind:'inflation_pressure',severity:b((m.inflation-8)/8),duration:5,source:'macro',effects:{supplierCost:.04,demand:-.03},expiresDay:w.day+5});if(m.creditAvailability<35)e.push({id:`credit-${w.day}`,day:w.day,kind:'credit_tightening',severity:b((35-m.creditAvailability)/35),duration:5,source:'macro',effects:{borrowingCost:.04},expiresDay:w.day+5});if(m.unemployment>10)e.push({id:`labor-${w.day}`,day:w.day,kind:'labor_slack',severity:b((m.unemployment-10)/8),duration:5,source:'macro',effects:{hiringDifficulty:-.1},expiresDay:w.day+5});for(const s of w.suppliers)if(hash(w.seed,w.day,s.id)<.025)e.push({id:`supply-${s.id}-${w.day}`,day:w.day,kind:'supplier_disruption',severity:.4+.5*hash(w.seed,w.day,s.id+'severity'),duration:2+Math.floor(hash(w.seed,w.day,s.id+'duration')*5),source:s.id,effects:{supplierCapacity:-.3,supplierCost:.08},expiresDay:w.day+5});return e;}

function competitorStep(w:Phase3World,price:number,quality:number){for(const c of w.competitors){const observed=price*c.perceptionAccuracy+100*(1-c.perceptionAccuracy);const pressure=price< c.price?1:c.price/Math.max(1,price);if(c.strategy==='cost_leader')c.price=clamp(c.price*.995+observed*.005,40,200);else if(c.strategy==='premium_specialist')c.quality=clamp(c.quality+.03*(quality-c.quality),40,100);else if(c.strategy==='fast_follower')c.price=clamp(c.price*.6+price*.4,40,200);else if(c.strategy==='innovator')c.quality=clamp(c.quality+.05,40,100);else if(c.strategy==='aggressive_entrant'&&w.marketSqueeze())c.price=clamp(c.price*.95,30,200);c.lastAction=pressure>.9?'respond':'hold';}}

// Kept separate from the state object so the competitor rule remains deterministic and pure.
function marketSqueeze(w:Phase3World){return w.markets[0].demandIndex>115||w.markets[0].marketShare>.2;}

export function advancePhase3World(previous:Phase3World,decision:Phase3Decision={}):Phase3World{
 const w=copy(previous);w.day++;w.explanations=[];w.telemetry=[];w.macro=updateMacro(w,decision);const effects:Phase3CausalEffect[]=[];
 const market=w.markets[0],ind=w.industries.find(x=>x.id===market.industry)??w.industries[1];const price=clamp(decision.price??market.averagePrice,1,100000);const q=clamp(w.reputation.productQuality+(decision.qualityInvestment??0)*.25+(decision.research??0)*.01,0,100);const brand=clamp(w.reputation.trust+(decision.marketing??0)*.15,0,100);
 const activeEvents=events(w);w.events=activeEvents;const disruption=activeEvents.filter(x=>x.kind==='supplier_disruption').reduce((v,x)=>v*(1-x.severity*.5),1);const econ=1+(w.macro.consumerConfidence-60)*.006;const season=1+.08*Math.sin(w.day/30);const priceEffect=Math.pow(Math.max(.25,price/100),-ind.demandElasticity);const competitors=w.competitors.reduce((v,c)=>v+c.marketShare*(c.price<price?.4:0),0);const comp=clamp(1-competitors*.8,.5,1.15);const demand=clamp(100*priceEffect*econ*season*comp*(.8+q*.006)*(.85+brand*.002)*(1+activeEvents.reduce((v,e)=>v+(e.effects.demand??0)*e.severity,0)),5,180);
 market.averagePrice=price;market.demandIndex=demand;market.trend=demand>108?'growing':demand<92?'declining':'stable';market.trendStrength=clamp(Math.abs(demand-100)/80,0,1);
 const hiring=Math.round(clamp(decision.hiring??0,-1000,1000));const layoffs=Math.round(clamp(decision.layoffs??0,0,1000));w.workforce.headcount=clamp(w.workforce.headcount+hiring-layoffs,1,10000);w.workforce.training=clamp(w.workforce.training+(decision.training??0),0,10000);w.workforce.skills=clamp(w.workforce.skills+(decision.training??0)*.002,0,100);w.workforce.workload=clamp(w.workforce.workload+(w.workforce.headcount>30?2:-1),0,100);w.workforce.morale=clamp(w.workforce.morale-(w.workforce.workload-60)*.025+(decision.training??0)*.0005-(layoffs>0?Math.min(10,layoffs*.3):0),0,100);w.workforce.productivity=clamp(w.workforce.productivity+(w.workforce.skills-60)*.015+(w.workforce.morale-60)*.02-(w.workforce.workload-70)*.04,10,120);w.workforce.retention=clamp(100-w.workforce.workload*.35+w.workforce.morale*.35,5,100);w.workforce.hiringDifficulty=clamp(w.macro.unemployment*5+w.regulation.pressure*20,5,95);
 const laborCapacity=w.workforce.headcount*w.workforce.productivity*.35;const materialCapacity=w.suppliers.reduce((v,s)=>v+s.availableCapacity,0)*disruption;const target=clamp(decision.productionTarget??demand*.75,0,100000);const output=Math.min(target,w.production.capacity,laborCapacity,materialCapacity,w.inventory.rawMaterials);const waste=output*(1-w.production.qualityYield);w.production.output=output;w.production.utilization=clamp(output/Math.max(1,w.production.capacity),0,1);w.production.unitCost=clamp(50+w.macro.commodityIndex*.05+(100-w.workforce.productivity)*.3,1,1000);w.production.equipmentCondition=clamp(w.production.equipmentCondition-(output/w.production.capacity)*.5+(decision.capacityInvestment??0)*.002,20,100);
 w.inventory.rawMaterials=clamp(w.inventory.rawMaterials-output+w.suppliers.reduce((v,s)=>v+s.availableCapacity*.35,0)*disruption,0,w.inventory.warehouseCapacity);w.inventory.finishedGoods=clamp(w.inventory.finishedGoods+output-waste,0,w.inventory.warehouseCapacity);w.inventory.waste+=waste;w.inventory.turnover=clamp(output/Math.max(1,w.inventory.finishedGoods),0,20);
 const sales=Math.min(demand*.75,w.inventory.finishedGoods);const revenue=sales*price;const materialCost=output*w.production.unitCost;const laborCost=w.workforce.headcount*(35+w.workforce.wagePressure);const marketing=clamp(decision.marketing??0,0,100000);const trainingCost=clamp(decision.training??0,0,100000);const compliance=w.regulation.complianceCost;const capex=clamp(decision.capacityInvestment??0,0,100000);const interest=w.capital.debt*(w.macro.interestRate/100)/365;const total=materialCost+laborCost+marketing+trainingCost+compliance+capex+interest;const cashFlow=revenue-total;
 if(decision.borrowing){const room=Math.max(0,w.capital.creditLimit-w.capital.debt);const amount=clamp(Math.min(decision.borrowing,room,w.capital.availableCapital),0,100000);w.capital.debt+=amount;w.finance.cash+=amount;effects.push({cause:'borrowing',effect:'cash',magnitude:amount,entity:'business'});}if(decision.repayment){const pay=clamp(Math.min(decision.repayment,w.capital.debt,w.finance.cash),0,100000);w.capital.debt-=pay;w.finance.cash-=pay;effects.push({cause:'repayment',effect:'debt',magnitude:-pay,entity:'business'});}
 w.finance={cash:clamp(w.finance.cash+cashFlow,0,1e12),revenue:w.finance.revenue+revenue,costs:w.finance.costs+total,grossProfit:revenue-materialCost,netCashFlow:cashFlow,debt:w.capital.debt,interestExpense:interest,valuation:0,inventoryValue:w.inventory.finishedGoods*w.production.unitCost,capex:w.finance.capex+capex};
 const satisfaction=clamp(w.reputation.productQuality*.35+w.reputation.service*.25+w.reputation.reliability*.2+w.reputation.trust*.2-(price-100)*.04,0,100);let purchases=0;for(const c of w.customers){const s=w.segments.find(x=>x.id===c.segment)!;const fit=b((100-price)/(100*s.priceSensitivity)+.5)*.4+b(q/100)*s.qualitySensitivity*.3+b(c.trust/100)*s.brandSensitivity*.3;c.awareness=clamp(c.awareness+(decision.marketing??0)*.01,0,100);c.consideration=clamp(c.consideration+(c.awareness-50)*.02,0,100);c.satisfaction=clamp(c.satisfaction+(satisfaction-c.satisfaction)*.12,0,100);c.priceMemory=clamp(c.priceMemory*.9+price*.1,1,100000);c.qualityMemory=clamp(c.qualityMemory*.9+q*.1,0,100);c.serviceMemory=clamp(c.serviceMemory*.9+w.reputation.service*.1,0,100);c.churnRisk=clamp((100-c.satisfaction)*.55+(100-c.loyalty)*.25+(price>c.priceMemory?10:0),0,100);const buy=fit*(.25+s.purchaseFrequency*.35)*(c.churnRisk<65?1:0);if(buy>.25){purchases++;c.purchases++;c.lastPurchaseDay=w.day;c.satisfaction=clamp(c.satisfaction+2,0,100);c.loyalty=clamp(c.loyalty+.5,0,100);c.stage=c.purchases>=8?'advocate':c.purchases>=4?'loyal':c.purchases>=2?'repeat':'acquired';}else if(c.churnRisk>75)c.stage='churned';}
 w.reputation={trust:clamp(w.reputation.trust+(satisfaction-70)*.025,0,100),productQuality:q,service:clamp(w.reputation.service+(decision.service??0)*.03,0,100),reliability:clamp(w.reputation.reliability+(output>0?0.03:-.08),0,100),ethics:clamp(w.reputation.ethics+(decision.ethics??0)*.02,0,100),employeeTreatment:clamp(w.reputation.employeeTreatment+(w.workforce.morale-60)*.02,0,100)};
 competitorStep(w,price,q);w.competitors.forEach(c=>c.marketShare=clamp(c.marketShare+(c.lastAction==='respond'?.002:-.0005),0,.8));const totalShare=w.competitors.reduce((v,c)=>v+c.marketShare,0)+.1;market.marketShare=clamp(.1/Math.max(.1,totalShare),0,1);
 w.capital.creditScore=clamp(70+(w.finance.cash>0?8:-15)-w.capital.debt/10000,10,95);w.capital.interestRate=w.macro.interestRate;w.capital.creditLimit=clamp(50000+w.capital.creditScore*1000,1000,200000);w.capital.investorConfidence=clamp(w.capital.investorConfidence+(cashFlow>0?1:-1)+(w.reputation.trust-50)*.01,0,100);w.capital.availableCapital=clamp(w.capital.creditLimit-w.capital.debt,0,200000);
 const profit=w.finance.grossProfit-w.finance.interestExpense;w.investor.lastDecision=profit>0&&w.capital.investorConfidence>55?'invest':w.capital.investorConfidence>40?'wait':'reject';w.investor.capitalAvailable=clamp(w.investor.capitalAvailable+(w.investor.lastDecision==='invest'?1000:-500),0,1e7);const multiple=clamp(3+w.macro.growthRate*.25+w.capital.investorConfidence*.01-(w.capital.debt/Math.max(1,w.finance.revenue))*2,1,12);w.finance.valuation=clamp(Math.max(1000,w.finance.revenue*multiple+Math.max(0,profit)*2-w.capital.debt),1000,1e12);w.capital.equityValue=w.finance.valuation-w.capital.debt;
 const growthRate=w.finance.revenue>0?w.finance.netCashFlow/Math.max(1,w.finance.revenue):0;if(w.finance.cash<=1&&w.capital.debt>0)w.lifecycle='crisis';else if(w.lifecycle==='launch'&&purchases>3)w.lifecycle='validation';else if(w.lifecycle==='validation'&&growthRate>.05)w.lifecycle='growth';else if(w.lifecycle==='growth'&&w.production.capacity>250)w.lifecycle='scale';else if(w.lifecycle==='scale'&&Math.abs(growthRate)<.02)w.lifecycle='maturity';if(w.lifecycle==='crisis'&&w.finance.cash>5000)w.lifecycle='survival';
 const supplierTight=1-materialCapacity/Math.max(1,w.suppliers.reduce((v,s)=>v+s.capacity,0));w.information={marketTrend:market.trendStrength*(market.trend==='declining'?-1:1),competitorSignals:w.competitors.map(c=>c.price-price),customerSentiment:satisfaction,supplierTightness:b(supplierTight),economicIndicators:copy(w.macro),confidence:clamp(.5+w.capital.investorConfidence*.005,0,1)};
 effects.push({cause:'price and market conditions',effect:'demand',magnitude:demand-100,entity:'market'},{cause:'demand and capacity',effect:'revenue',magnitude:revenue,entity:'business'},{cause:'workforce and training',effect:'productivity',magnitude:w.workforce.productivity,entity:'workforce'});if(activeEvents.length)effects.push({cause:'world events',effect:'supply and demand',magnitude:activeEvents.length,entity:'world'});w.explanations.push({day:w.day,outcome:`revenue ${revenue>=0?'+':''}${Math.round(revenue)}`,effects});w.telemetry.push({day:w.day,decision:JSON.stringify(decision),causes:effects.map(x=>x.cause),effects:effects.map(x=>x.effect),entity:'business',version:1,seed:w.seed});validatePhase3World(w);return w;
}

// Compatibility helper for older integrations that accidentally called the method on the world.
export function marketSqueeze(w:Phase3World){return marketSqueeze(w);}

export function validatePhase3World(w:Phase3World):true{if(w.version!==1||!Number.isFinite(w.day)||w.day<1)throw new Error('Invalid Phase 3 world header');const nums=[w.macro.inflation,w.macro.interestRate,w.macro.growthRate,w.macro.unemployment,w.macro.consumerConfidence,w.macro.businessConfidence,w.macro.creditAvailability,w.macro.commodityIndex,w.finance.cash,w.finance.debt,w.finance.valuation,w.inventory.rawMaterials,w.inventory.finishedGoods,w.production.capacity,w.production.output,w.workforce.headcount,w.workforce.productivity];if(nums.some(x=>!Number.isFinite(x)))throw new Error('Phase 3 world contains non-finite state');if(w.capital.debt<0||w.finance.debt<0||w.inventory.rawMaterials<0||w.inventory.finishedGoods<0||w.production.output<0)throw new Error('Phase 3 conservation constraint violated');if(w.markets.some(m=>m.marketShare<0||m.marketShare>1))throw new Error('Market share out of bounds');if(w.customers.some(c=>c.churnRisk<0||c.churnRisk>100))throw new Error('Customer state out of bounds');return true;}

export function advancePhase3FromSimulation(state:SimulationState,seed=state.meta?.seed??1):Phase3World{const w=createPhase3World(seed);const business=state.business;return advancePhase3World({...w,day:Math.max(1,business.day),finance:{...w.finance,cash:Math.max(0,business.cash),revenue:Math.max(0,business.revenue),costs:Math.max(0,business.expenses),debt:Math.max(0,state.operations?.debt??0),valuation:Math.max(1000,state.financials?.valuation??w.finance.valuation)}},{price:state.operations?.price,marketing:state.operations?.marketingBudget});}

export function runPhase3Days(initial:Phase3World,days:number,decisions:Phase3Decision[]=[]):Phase3World[]{const out:Phase3World[]=[copy(initial)];let w=initial;for(let i=0;i<days;i++){w=advancePhase3World(w,decisions[i]??{});out.push(w);}return out;}
export function deterministicReplay(seed:number,days:number,decisions:Phase3Decision[]=[]){const a=runPhase3Days(createPhase3World(seed),days,decisions).at(-1);const b=runPhase3Days(createPhase3World(seed),days,decisions).at(-1);return JSON.stringify(a)===JSON.stringify(b);}
export interface Phase3StrategyResult {strategy:string;finalCash:number;finalRevenue:number;valuation:number;survived:boolean;}
export function comparePhase3Strategies(seed=1,days=365):Phase3StrategyResult[]{const plans:Record<string,Phase3Decision>={premium:{price:125,qualityInvestment:25,marketing:10},low_cost:{price:75,marketing:5},growth:{price:105,hiring:3,capacityInvestment:1000,borrowing:5000},conservative:{price:100,repayment:100,marketing:2},marketing:{price:100,marketing:50},research:{price:105,research:40,qualityInvestment:20}};return Object.entries(plans).map(([strategy,d])=>{const w=runPhase3Days(createPhase3World(seed),days,Array.from({length:days},()=>d)).at(-1)!;return{strategy,finalCash:w.finance.cash,finalRevenue:w.finance.revenue,valuation:w.finance.valuation,survived:w.lifecycle!=='failed'};});}
export interface Phase3CalibrationReport {runs:number;survivalRate:number;averageValuation:number;averageChurn:number;averageDebt:number;inflationRange:[number,number];}
export function calibratePhase3(runs=100,days=365):Phase3CalibrationReport{let survivors=0,totalVal=0,totalChurn=0,totalDebt=0,minInf=Infinity,maxInf=-Infinity;for(let i=0;i<runs;i++){const w=runPhase3Days(createPhase3World(i+1),days).at(-1)!;if(w.lifecycle!=='failed')survivors++;totalVal+=w.finance.valuation;totalDebt+=w.capital.debt;totalChurn+=w.customers.filter(c=>c.stage==='churned').length/w.customers.length;minInf=Math.min(minInf,w.macro.inflation);maxInf=Math.max(maxInf,w.macro.inflation);}return{runs,survivalRate:survivors/runs,averageValuation:totalVal/runs,averageChurn:totalChurn/runs,averageDebt:totalDebt/runs,inflationRange:[minInf,maxInf]};}

export function phase3InformationReport(w:Phase3World):Phase3Information{return copy(w.information);}
export function phase3Snapshot(w:Phase3World):Phase3World{return copy(w);}
export function restorePhase3Snapshot(snapshot:Phase3World):Phase3World{validatePhase3World(snapshot);return copy(snapshot);}
