import { advancePhase3World, createPhase3World, type Phase3Decision, type Phase3Event, type Phase3Industry, type Phase3World } from './phase3';

export type DeepStrategy='low_price'|'premium'|'growth'|'marketing'|'research'|'conservative';
export type DeepHorizon='today'|'week'|'month'|'long_term';
export interface DeepPlan{strategy:DeepStrategy;horizon:DeepHorizon;priceTarget:number;capacityTarget:number;inventoryTarget:number;cashBuffer:number;riskBudget:number;}
export interface DeepRegulation{taxRate:number;qualityStandard:number;laborStandard:number;environmentalPressure:number;complianceBudget:number;}
export interface DeepCustomerMemory{price:number;quality:number;service:number;delivery:number;trust:number;lastDay:number;}
export interface DeepCustomerAgent{id:string;segment:string;income:number;priceSensitivity:number;qualitySensitivity:number;brandSensitivity:number;switchingCost:number;memory:DeepCustomerMemory;stage:'awareness'|'consideration'|'acquired'|'repeat'|'loyal'|'advocate'|'churned';}
export interface DeepSupplierAgent{id:string;capacity:number;available:number;unitCost:number;reliability:number;quality:number;leadTime:number;relationship:number;paymentTrust:number;priority:number;}
export interface DeepCompetitorAgent{id:string;strategy:'cost_leader'|'premium_specialist'|'fast_follower'|'innovator'|'aggressive_entrant'|'conservative_incumbent';cash:number;capacity:number;price:number;quality:number;marketing:number;belief:number;lastDecision:string;}
export interface DeepInvestorAgent{id:string;riskTolerance:number;growthPreference:number;profitPreference:number;patience:number;capital:number;decision:'invest'|'wait'|'reject';}
export interface DeepWorkforce{headcount:number;skillPool:number;morale:number;workload:number;productivity:number;turnoverRisk:number;hiringPool:number;trainingHours:number;wageIndex:number;}
export interface DeepFinance{cash:number;debt:number;interest:number;revenue:number;operatingCost:number;capex:number;freeCashFlow:number;valuation:number;creditScore:number;}
export interface DeepProduction{capacity:number;equipment:number;materials:number;output:number;yield:number;waste:number;unitCost:number;warehouse:number;}
export interface DeepMarket{addressableDemand:number;servedDemand:number;industryGrowth:number;seasonality:number;priceIndex:number;competitivePressure:number;}
export interface DeepCrisis{kind:'cash'|'supply'|'workforce'|'reputation'|'market'|'debt';severity:number;started:number;expires:number;causes:string[];}
export interface DeepTrace{day:number;decision:Phase3Decision;cause:string;effect:string;magnitude:number;delay:number;entity:string;}
export interface DeepWorld extends Phase3World{deep:{plan:DeepPlan;regulation:DeepRegulation;customers:DeepCustomerAgent[];suppliers:DeepSupplierAgent[];competitors:DeepCompetitorAgent[];investors:DeepInvestorAgent[];workforce:DeepWorkforce;finance:DeepFinance;production:DeepProduction;market:DeepMarket;crises:DeepCrisis[];traces:DeepTrace[];pending:DeepTrace[];version:1;};}

const c=(v:number,min=0,max=1)=>Number.isFinite(v)?Math.min(max,Math.max(min,v)):min;
const h=(seed:number,day:number,key:string)=>{let x=(seed^day)>>>0;for(let i=0;i<key.length;i++)x=Math.imul(x^key.charCodeAt(i),16777619)>>>0;return x/4294967296;};
const clone=<T>(x:T):T=>JSON.parse(JSON.stringify(x)) as T;

function makeDeep(base:Phase3World):DeepWorld{const seg=base.segments;return Object.assign(base,{deep:{version:1,plan:{strategy:'conservative',horizon:'week',priceTarget:100,capacityTarget:base.production.capacity,inventoryTarget:base.inventory.finishedGoods,cashBuffer:5000,riskBudget:.2},regulation:{taxRate:.2,qualityStandard:60,laborStandard:50,environmentalPressure:base.regulation.pressure,complianceBudget:base.regulation.complianceCost},customers:base.customers.map((x,i)=>({id:x.id,segment:x.segment,income:800+((i*137)%1200),priceSensitivity:seg.find(s=>s.id===x.segment)?.priceSensitivity??1,qualitySensitivity:seg.find(s=>s.id===x.segment)?.qualitySensitivity??1,brandSensitivity:seg.find(s=>s.id===x.segment)?.brandSensitivity??1,switchingCost:seg.find(s=>s.id===x.segment)?.switchingCost??.2,memory:{price:x.priceMemory,quality:x.qualityMemory,service:x.serviceMemory,delivery:70,trust:x.trust,lastDay:x.lastPurchaseDay},stage:x.stage})),suppliers:base.suppliers.map(x=>({id:x.id,capacity:x.capacity,available:x.availableCapacity,unitCost:x.unitCost,reliability:x.reliability,quality:x.quality,leadTime:x.leadTime,relationship:x.relationship,paymentTrust:x.financialHealth,priority:x.relationship})),competitors:base.competitors.map(x=>({id:x.id,strategy:x.strategy,cash:x.cash,capacity:120,price:x.price,quality:x.quality,marketing:x.marketing,belief:x.perceptionAccuracy,lastDecision:x.lastAction})),investors:[{id:'investor-1',riskTolerance:.45,growthPreference:.65,profitPreference:.55,patience:.7,capital:50000,decision:'wait'},{id:'investor-2',riskTolerance:.7,growthPreference:.8,profitPreference:.35,patience:.45,capital:100000,decision:'wait'}],workforce:{headcount:base.workforce.headcount,skillPool:base.workforce.skills,morale:base.workforce.morale,workload:base.workforce.workload,productivity:base.workforce.productivity,turnoverRisk:100-base.workforce.retention,hiringPool:c(base.macro.unemployment/20)*100,trainingHours:base.workforce.training,wageIndex:100+base.workforce.wagePressure},finance:{cash:base.finance.cash,debt:base.capital.debt,interest:base.macro.interestRate,revenue:base.finance.revenue,operatingCost:base.finance.costs,capex:base.finance.capex,freeCashFlow:base.finance.netCashFlow,valuation:base.finance.valuation,creditScore:base.capital.creditScore},production:{capacity:base.production.capacity,equipment:base.production.equipmentCondition,materials:base.inventory.rawMaterials,output:base.production.output,yield:base.production.qualityYield,waste:base.inventory.waste,unitCost:base.production.unitCost,warehouse:base.inventory.warehouseCapacity},market:{addressableDemand:base.markets[0].size,servedDemand:base.markets[0].demandIndex,industryGrowth:base.macro.growthRate,seasonality:0,priceIndex:base.markets[0].averagePrice,competitivePressure:base.industries.find(i=>i.id===base.markets[0].industry)?.competitionIntensity??.5},crises:[],traces:[],pending:[]}})}

export function createDeepPhase3World(seed=1,industry:Phase3Industry='retail'):DeepWorld{return makeDeep(createPhase3World(seed,industry));}

function applyDelayed(w:DeepWorld){const due=w.deep.pending.filter(t=>t.day<=w.day);w.deep.pending=w.deep.pending.filter(t=>t.day>w.day);for(const t of due){w.deep.traces.push(t);}}
function generateDeepEvents(w:DeepWorld):Phase3Event[]{const e=[...w.events];if(w.deep.finance.cash<w.deep.plan.cashBuffer)e.push({id:`cash-crisis-${w.day}`,day:w.day,kind:'cash_crisis',severity:c((w.deep.plan.cashBuffer-w.deep.finance.cash)/Math.max(1,w.deep.plan.cashBuffer)),duration:3,source:'finance',effects:{investment:-.2,demand:-.02},expiresDay:w.day+3});if(w.deep.production.materials<w.deep.production.capacity*.15)e.push({id:`material-crisis-${w.day}`,day:w.day,kind:'material_shortage',severity:c(1-w.deep.production.materials/Math.max(1,w.deep.production.capacity*.15)),duration:3,source:'supply',effects:{supplierCapacity:-.25},expiresDay:w.day+3});return e}

export function advanceDeepPhase3World(previous:DeepWorld,decision:Phase3Decision={}):DeepWorld{let w=clone(previous);applyDelayed(w);w=makeDeep(advancePhase3World(w,decision));w.deep.plan={...previous.deep.plan};w.deep.regulation={...previous.deep.regulation};w.deep.traces=previous.deep.traces.slice(-1000);w.deep.pending=previous.deep.pending.slice(-500);w.deep.crises=previous.deep.crises.filter(x=>x.expires>=w.day);w.deep.finance.cash=w.finance.cash;w.deep.finance.debt=w.capital.debt;w.deep.finance.interest=w.macro.interestRate;w.deep.finance.revenue=w.finance.revenue;w.deep.finance.operatingCost=w.finance.costs;w.deep.finance.capex=w.finance.capex;w.deep.finance.freeCashFlow=w.finance.netCashFlow;w.deep.finance.valuation=w.finance.valuation;w.deep.finance.creditScore=w.capital.creditScore;w.deep.production.capacity=w.production.capacity;w.deep.production.equipment=w.production.equipmentCondition;w.deep.production.materials=w.inventory.rawMaterials;w.deep.production.output=w.production.output;w.deep.production.yield=w.production.qualityYield;w.deep.production.waste=w.inventory.waste;w.deep.production.unitCost=w.production.unitCost;w.deep.production.warehouse=w.inventory.warehouseCapacity;w.deep.market.addressableDemand=w.markets[0].size;w.deep.market.servedDemand=w.markets[0].demandIndex;w.deep.market.industryGrowth=w.macro.growthRate;w.deep.market.priceIndex=w.markets[0].averagePrice;w.deep.market.competitivePressure= w.industries.find(i=>i.id===w.markets[0].industry)?.competitionIntensity??.5;
 const price= w.markets[0].averagePrice;const satisfaction=w.information.customerSentiment;for(const customer of w.deep.customers){const memory=customer.memory;const priceGap=(price-memory.price)/Math.max(1,memory.price);const qualityGap=(w.reputation.productQuality-memory.quality)/100;const serviceGap=(w.reputation.service-memory.service)/100;const value=-priceGap*customer.priceSensitivity+qualityGap*customer.qualitySensitivity+serviceGap*.5+customer.brandSensitivity*(w.reputation.trust-memory.trust)/100;const p=c(.18+value*.22+customer.switchingCost*.05);if(h(w.seed,w.day,customer.id)<p){customer.memory={price,quality:w.reputation.productQuality,service:w.reputation.service,delivery:w.reputation.reliability,trust:w.reputation.trust,lastDay:w.day};customer.stage=customer.stage==='awareness'?'acquired':customer.stage==='acquired'?'repeat':customer.stage==='repeat'?'loyal':customer.stage==='loyal'?'advocate':customer.stage;}}
 const supplyPressure=1-w.deep.production.materials/Math.max(1,w.deep.production.capacity);for(const supplier of w.deep.suppliers){supplier.available=c(supplier.available/supplier.capacity)*supplier.capacity;supplier.relationship=c(supplier.relationship/100)*100;if(decision.borrowing&&w.deep.finance.cash<w.deep.plan.cashBuffer)supplier.paymentTrust=c(supplier.paymentTrust-.5/100)*100;if(supplyPressure>.6)supplier.unitCost*=1+.02*supplyPressure;supplier.reliability=c(supplier.reliability/100)*100;}
 const demandPressure=w.markets[0].demandIndex/100;for(const comp of w.deep.competitors){const observed=comp.price+(price-comp.price)*comp.belief;const gain=(demandPressure-.9)*comp.aggression;switch(comp.strategy){case'cost_leader':comp.price=c(observed*.985,.3,200);break;case'premium_specialist':comp.quality=c(comp.quality/100+.01*gain)*100;break;case'fast_follower':comp.price=observed;break;case'innovator':comp.quality=c(comp.quality/100+.015)*100;comp.marketing=Math.max(0,comp.marketing+gain*2);break;case'aggressive_entrant':comp.price=Math.max(30,observed-3*gain);break;default:comp.price=comp.price*.995+observed*.005}comp.lastDecision=comp.price<price?'attack':'hold';}
 const turnover=c((w.deep.workforce.workload-65)/35)*.2+c((60-w.deep.workforce.morale)/60)*.15;w.deep.workforce.turnoverRisk=c(turnover,0,1)*100;w.deep.workforce.hiringPool=c(w.macro.unemployment/20)*100;w.deep.workforce.wageIndex=100+w.workforce.wagePressure;if(decision.training)w.deep.workforce.trainingHours+=decision.training;if(decision.hiring)w.deep.workforce.headcount=w.workforce.headcount;w.deep.workforce.skillPool=w.workforce.skills;w.deep.workforce.morale=w.workforce.morale;w.deep.workforce.productivity=w.workforce.productivity;
 for(const investor of w.deep.investors){const growth=w.macro.growthRate/8;const profitability=w.finance.netCashFlow/Math.max(1,w.finance.revenue);const risk=c(w.capital.debt/Math.max(1,w.finance.revenue),0,1);const score=growth*investor.growthPreference+profitability*investor.profitPreference-risk*(1-investor.riskTolerance);investor.decision=score>.08&&w.capital.investorConfidence>50?'invest':score>-.02?'wait':'reject';if(investor.decision==='invest')investor.capital=Math.max(0,investor.capital-1000);}
 const events=generateDeepEvents(w);w.events=events;for(const e of events){if(e.kind==='cash_crisis'&&e.severity>.5)w.deep.crises.push({kind:'cash',severity:e.severity,started:w.day,expires:e.expiresDay,causes:['cash below buffer','financing pressure']});if(e.kind==='material_shortage'&&e.severity>.5)w.deep.crises.push({kind:'supply',severity:e.severity,started:w.day,expires:e.expiresDay,causes:['low materials','capacity constraint']});}
 if(w.deep.regulation.qualityStandard>w.reputation.productQuality)w.regulation.violationRisk=c((w.deep.regulation.qualityStandard-w.reputation.productQuality)/100);else w.regulation.violationRisk=c(w.regulation.violationRisk*.95);
 const direct={day:w.day,decision,causes:['world conditions','player decision'],effects:['demand','supply','finance','reputation'],entity:'deep-world',version:1 as const,seed:w.seed};w.telemetry.push(direct);w.deep.traces.push({day:w.day,decision,cause:'market and world conditions',effect:'business outcome',magnitude:w.finance.netCashFlow,delay:0,entity:'business'});return w;}

export interface DeepValidationReport{errors:string[];warnings:string[]}
export function validateDeepPhase3World(w:DeepWorld):DeepValidationReport{const errors:string[]=[];const warnings:string[]=[];if(!Number.isFinite(w.deep.finance.cash)||!Number.isFinite(w.deep.finance.valuation))errors.push('non-finite finance');if(w.deep.production.output>w.deep.production.capacity+1e-9)errors.push('production exceeds capacity');if(w.deep.workforce.headcount<1)errors.push('invalid workforce');if(w.deep.competitors.some(x=>x.marketShare<0||x.marketShare>1))warnings.push('competitor share requires normalization');if(w.deep.finance.debt<0)errors.push('negative debt');if(w.deep.production.materials<0)errors.push('negative materials');return{errors,warnings};}
export function runDeepPhase3(initial:DeepWorld,days:number,decisions:Phase3Decision[]=[]):DeepWorld[]{const result=[clone(initial)];let w=initial;for(let i=0;i<days;i++){w=advanceDeepPhase3World(w,decisions[i]??{});const report=validateDeepPhase3World(w);if(report.errors.length)throw new Error(report.errors.join('; '));result.push(clone(w));}return result;}
export function runDeepMonteCarlo(runs=100,days=365){const outcomes=[] as Array<{seed:number;cash:number;valuation:number;survived:boolean}>;for(let seed=1;seed<=runs;seed++){const w=runDeepPhase3(createDeepPhase3World(seed),days)[days];outcomes.push({seed,cash:w.finance.cash,valuation:w.finance.valuation,survived:w.lifecycle!=='failed'});}const survived=outcomes.filter(x=>x.survived).length;return{runs,days,survivalRate:survived/runs,averageCash:outcomes.reduce((a,x)=>a+x.cash,0)/runs,averageValuation:outcomes.reduce((a,x)=>a+x.valuation,0)/runs,minCash:Math.min(...outcomes.map(x=>x.cash)),maxCash:Math.max(...outcomes.map(x=>x.cash))};}
export function runDeepAdversarialSuite(seed=1){const cases:Phase3Decision[]=[{price:1e99},{price:0},{price:1},{borrowing:1e99},{repayment:1e99},{hiring:1e99},{layoffs:1e99},{marketing:1e99},{capacityInvestment:1e99},{productionTarget:1e99}];const failures:string[]=[];for(const d of cases){try{const w=runDeepPhase3(createDeepPhase3World(seed),30,Array.from({length:30},()=>d))[30];const r=validateDeepPhase3World(w);if(r.errors.length)failures.push(r.errors.join('; '));}catch(e){failures.push(e instanceof Error?e.message:'unknown failure');}}return{cases:cases.length,failures,passed:failures.length===0};}
