import type { SimulationState } from '@enterpriseverse/types';

export type Phase3Industry = 'technology' | 'retail' | 'manufacturing' | 'food' | 'services' | 'logistics';
export type Phase3Trend = 'growing' | 'stable' | 'declining';
export type Phase3CompetitorStrategy = 'cost_leader' | 'premium_specialist' | 'fast_follower' | 'innovator' | 'aggressive_entrant' | 'conservative_incumbent';
export type Phase3CustomerSegment = 'budget' | 'mainstream' | 'premium' | 'enterprise';

export interface Phase3MacroEconomy { day:number; inflation:number; interestRate:number; growthRate:number; unemployment:number; consumerConfidence:number; businessConfidence:number; creditAvailability:number; commodityIndex:number; }
export interface Phase3IndustryState { id:Phase3Industry; capitalIntensity:number; laborIntensity:number; baseMargin:number; demandElasticity:number; competitionIntensity:number; growthRate:number; supplierConcentration:number; regulatoryPressure:number; }
export interface Phase3MarketState { id:string; industry:Phase3Industry; size:number; trend:Phase3Trend; trendStrength:number; averagePrice:number; demandIndex:number; }
export interface Phase3CustomerSegmentState { id:Phase3CustomerSegment; population:number; priceSensitivity:number; qualitySensitivity:number; brandSensitivity:number; switchingCost:number; loyalty:number; purchaseFrequency:number; incomeSensitivity:number; }
export interface Phase3CustomerState { id:string; segment:Phase3CustomerSegment; awareness:number; consideration:number; satisfaction:number; loyalty:number; trust:number; priceMemory:number; qualityMemory:number; serviceMemory:number; churnRisk:number; purchases:number; }
export interface Phase3SupplierState { id:string; capacity:number; availableCapacity:number; unitCost:number; quality:number; reliability:number; leadTime:number; relationship:number; financialHealth:number; }
export interface Phase3WorkforceState { headcount:number; skills:number; morale:number; workload:number; productivity:number; retention:number; wagePressure:number; hiringDifficulty:number; }
export interface Phase3CompetitorState { id:string; strategy:Phase3CompetitorStrategy; cash:number; marketShare:number; price:number; quality:number; marketing:number; riskTolerance:number; capitalAccess:number; timeHorizon:number; aggression:number; perceptionAccuracy:number; }
export interface Phase3CapitalState { creditScore:number; debt:number; interestRate:number; creditLimit:number; investorConfidence:number; availableCapital:number; }
export interface Phase3FinanceState { cash:number; revenue:number; costs:number; grossProfit:number; netCashFlow:number; debt:number; interestExpense:number; valuation:number; }
export interface Phase3ReputationState { trust:number; productQuality:number; service:number; reliability:number; ethics:number; employeeTreatment:number; }
export interface Phase3Event { id:string; day:number; kind:string; severity:number; duration:number; source:string; effects:Record<string,number>; }
export interface Phase3CausalEffect { cause:string; effect:string; magnitude:number; entity:string; }
export interface Phase3Explainability { day:number; outcome:string; effects:Phase3CausalEffect[]; }
export interface Phase3World { version:1; seed:number; day:number; macro:Phase3MacroEconomy; industries:Phase3IndustryState[]; markets:Phase3MarketState[]; customers:Phase3CustomerState[]; segments:Phase3CustomerSegmentState[]; suppliers:Phase3SupplierState[]; workforce:Phase3WorkforceState; competitors:Phase3CompetitorState[]; capital:Phase3CapitalState; finance:Phase3FinanceState; reputation:Phase3ReputationState; events:Phase3Event[]; explanations:Phase3Explainability[]; }

const INDUSTRIES:Phase3IndustryState[] = [
 {id:'technology',capitalIntensity:.55,laborIntensity:.65,baseMargin:.22,demandElasticity:1.25,competitionIntensity:.75,growthRate:.045,supplierConcentration:.35,regulatoryPressure:.3},
 {id:'retail',capitalIntensity:.4,laborIntensity:.7,baseMargin:.1,demandElasticity:1.55,competitionIntensity:.85,growthRate:.02,supplierConcentration:.45,regulatoryPressure:.35},
 {id:'manufacturing',capitalIntensity:.85,laborIntensity:.55,baseMargin:.14,demandElasticity:1.1,competitionIntensity:.65,growthRate:.025,supplierConcentration:.6,regulatoryPressure:.55},
 {id:'food',capitalIntensity:.45,laborIntensity:.75,baseMargin:.12,demandElasticity:1.35,competitionIntensity:.8,growthRate:.018,supplierConcentration:.5,regulatoryPressure:.5},
 {id:'services',capitalIntensity:.25,laborIntensity:.9,baseMargin:.18,demandElasticity:1.2,competitionIntensity:.7,growthRate:.03,supplierConcentration:.2,regulatoryPressure:.2},
 {id:'logistics',capitalIntensity:.8,laborIntensity:.65,baseMargin:.11,demandElasticity:1.05,competitionIntensity:.7,growthRate:.035,supplierConcentration:.4,regulatoryPressure:.45},
];
const SEGMENTS:Phase3CustomerSegmentState[] = [
 {id:'budget',population:35,priceSensitivity:1.45,qualitySensitivity:.55,brandSensitivity:.45,switchingCost:.1,loyalty:.35,purchaseFrequency:.7,incomeSensitivity:1.1},
 {id:'mainstream',population:40,priceSensitivity:1,qualitySensitivity:1,brandSensitivity:.8,switchingCost:.25,loyalty:.5,purchaseFrequency:1,incomeSensitivity:.8},
 {id:'premium',population:18,priceSensitivity:.55,qualitySensitivity:1.35,brandSensitivity:1.3,switchingCost:.35,loyalty:.65,purchaseFrequency:.8,incomeSensitivity:.65},
 {id:'enterprise',population:7,priceSensitivity:.45,qualitySensitivity:1.45,brandSensitivity:1.1,switchingCost:.7,loyalty:.72,purchaseFrequency:.55,incomeSensitivity:.5},
];
const clamp=(v:number,min=0,max=100)=>Number.isFinite(v)?Math.min(max,Math.max(min,v)):min;
const bounded=(v:number,min=0,max=1)=>clamp(v,min,max);
const hash=(seed:number,day:number,key:string)=>{let h=(seed^day)>>>0;for(let i=0;i<key.length;i++)h=Math.imul(h^key.charCodeAt(i),16777619)>>>0;return (h>>>0)/4294967296;};
const shock=(seed:number,day:number,key:string,amplitude=.02)=>(hash(seed,day,key)-.5)*2*amplitude;
const elasticityFactor=(relativePrice:number,elasticity:number)=>Math.pow(Math.max(.25,relativePrice),-elasticity);

export function createPhase3World(seed=1, industry:Phase3Industry='retail'):Phase3World {
 const ind=INDUSTRIES.find(x=>x.id===industry)??INDUSTRIES[1];
 const competitors:Phase3CompetitorState[]=[
  ['cost_leader',.18],['premium_specialist',.14],['fast_follower',.12],['innovator',.1]
 ].map(([strategy,share],i)=>({id:`competitor-${i+1}`,strategy:strategy as Phase3CompetitorStrategy,cash:50000+i*15000,marketShare:share as number,price:100,quality:70+i*6,marketing:20,riskTolerance:.25+i*.15,capitalAccess:.45+i*.1,timeHorizon:.5+i*.08,aggression:.3+i*.12,perceptionAccuracy:.8}));
 const customers=Array.from({length:40},(_,i)=>{const s=SEGMENTS[i%SEGMENTS.length];return{id:`customer-${i+1}`,segment:s.id,awareness:40,consideration:35,satisfaction:70,loyalty:s.loyalty*100,trust:60,priceMemory:100,qualityMemory:70,serviceMemory:70,churnRisk:15,purchases:0};});
 const suppliers=Array.from({length:4},(_,i)=>({id:`supplier-${i+1}`,capacity:100+i*35,availableCapacity:100+i*35,unitCost:55+i*3,quality:72+i*5,reliability:70+i*6,leadTime:2+i,relationship:50,financialHealth:75}));
 return {version:1,seed,day:1,macro:{day:1,inflation:3,interestRate:6,growthRate:2.5,unemployment:5,consumerConfidence:65,businessConfidence:65,creditAvailability:70,commodityIndex:100},industries:INDUSTRIES.map(x=>({...x})),markets:[{id:'primary',industry,size:100000,trend:'stable',trendStrength:0,demandIndex:100,averagePrice:100}],customers,segments:SEGMENTS.map(x=>({...x})),suppliers,workforce:{headcount:10,skills:70,morale:72,workload:55,productivity:70,retention:85,wagePressure:3,hiringDifficulty:30},competitors,capital:{creditScore:70,debt:0,interestRate:6,creditLimit:50000,investorConfidence:60,availableCapital:20000},finance:{cash:20000,revenue:0,costs:0,grossProfit:0,netCashFlow:0,debt:0,interestExpense:0,valuation:50000},reputation:{trust:50,productQuality:70,service:70,reliability:70,ethics:70,employeeTreatment:70},events:[],explanations:[]};
}

export interface Phase3Decision { price?:number; qualityInvestment?:number; marketing?:number; hiring?:number; training?:number; capacityInvestment?:number; inventoryTarget?:number; borrowing?:number; repayment?:number; research?:number; ethics?:number; service?:number; }

function updateMacro(w:Phase3World,d:Phase3Decision):Phase3MacroEconomy {
 const m=w.macro;const inflation=clamp(m.inflation + (m.commodityIndex-100)*.012 + shock(w.seed,w.day,'inflation',.15),0,25);const rate=clamp(m.interestRate + (inflation-3)*.08 - (m.growthRate-2.5)*.04,0,20);const growth=clamp(m.growthRate + (m.consumerConfidence-60)*.012 - (rate-6)*.08 + shock(w.seed,w.day,'growth',.12),-8,8);const unemployment=clamp(m.unemployment-(growth-2.5)*.06+shock(w.seed,w.day,'unemployment',.1),2,20);const confidence=clamp(m.consumerConfidence+(growth-2.5)*.8-(inflation-3)*.5-(d.price?Math.max(0,d.price-100)*.01:0),10,95);return{day:w.day,inflation,interestRate:rate,growthRate:growth,unemployment,consumerConfidence:confidence,businessConfidence:clamp(m.businessConfidence+(growth-2.5)*.7-(rate-6)*.35,10,95),creditAvailability:clamp(m.creditAvailability-(rate-6)*.7-(w.capital.debt/100000)*8,10,95),commodityIndex:clamp(m.commodityIndex+(inflation-3)*.45+shock(w.seed,w.day,'commodity',.5),70,160)};
}
function generateEvents(w:Phase3World):Phase3Event[]{const m=w.macro;const events:Phase3Event[]=[];if(m.inflation>8)events.push({id:`inflation-${w.day}`,day:w.day,kind:'inflation_pressure',severity:bounded((m.inflation-8)/10),duration:5,source:'macro',effects:{supplierCost:.04,demand:-.03}});if(m.unemployment>10)events.push({id:`labor-${w.day}`,day:w.day,kind:'labor_slack',severity:bounded((m.unemployment-10)/8),duration:5,source:'macro',effects:{hiringDifficulty:-.1}});if(m.creditAvailability<35)events.push({id:`credit-${w.day}`,day:w.day,kind:'credit_tightening',severity:bounded((35-m.creditAvailability)/35),duration:5,source:'macro',effects:{borrowingCost:.04}});w.suppliers.forEach(s=>{const p=hash(w.seed,w.day,s.id);if(p<.025){events.push({id:`supply-${s.id}-${w.day}`,day:w.day,kind:'supplier_disruption',severity:.4+.5*hash(w.seed,w.day,s.id+'severity'),duration:2+Math.floor(hash(w.seed,w.day,s.id+'duration')*5),source:s.id,effects:{supplierCapacity:-.3,supplierCost:.08}});}});return events;}

export function advancePhase3World(previous:Phase3World, decision:Phase3Decision={}):Phase3World {
 const w:Phase3World=structuredClone(previous);w.day+=1;w.events=[];w.explanations=[];
 const effects:Phase3CausalEffect[]=[];
 w.macro=updateMacro(w,decision);
 if(decision.borrowing) {const amount=clamp(decision.borrowing,0,100000);const available=Math.min(amount,w.capital.creditLimit-w.capital.debt,w.capital.availableCapital);w.capital.debt+=Math.max(0,available);w.finance.cash+=Math.max(0,available);effects.push({cause:'financing decision',effect:'cash',magnitude:available,entity:'business'});}
 if(decision.repayment){const pay=Math.min(clamp(decision.repayment,0,100000),w.finance.cash,w.capital.debt);w.finance.cash-=pay;w.capital.debt-=pay;effects.push({cause:'debt repayment',effect:'debt',magnitude:-pay,entity:'business'});}
 const events=generateEvents(w);w.events=events;
 const industry=w.industries.find(i=>i.id===w.markets[0].industry)!;const price=decision.price&&decision.price>1?decision.price:w.markets[0].averagePrice;const quality=clamp(w.reputation.productQuality+(decision.qualityInvestment??0)*.35);const brand=clamp(w.reputation.trust+(decision.marketing??0)*.18);
 const eventDemand=events.reduce((x,e)=>x+(e.effects.demand??0)*e.severity,0);const economicDemand=1+(w.macro.consumerConfidence-60)*.006;const seasonal=1+.08*Math.sin(w.day/30);const priceEffect=elasticityFactor(price/100,industry.demandElasticity);const competitivePressure=w.competitors.reduce((x,c)=>x+c.marketShare*(c.price<price?.4:0),0);const competitiveEffect=clamp(1-competitivePressure*.8,.5,1.15);const qualityEffect=bounded(.8+(quality-50)*.006,.65,1.25);const brandEffect=bounded(.85+brand*.002,.75,1.1);const demandIndex=clamp(100*priceEffect*economicDemand*seasonal*competitiveEffect*qualityEffect*brandEffect*(1+eventDemand),10,180);
 const market=w.markets[0];market.averagePrice=clamp(price,1,100000);market.demandIndex=demandIndex;market.trend=demandIndex>108?'growing':demandIndex<92?'declining':'stable';market.trendStrength=Math.abs(demandIndex-100)/80;
 const units=Math.max(0,Math.round(demandIndex*.75));const supplyCapacity=w.suppliers.reduce((x,s)=>x+s.availableCapacity,0)+w.workforce.headcount*w.workforce.productivity*.35;const disruptionFactor=events.filter(e=>e.kind==='supplier_disruption').reduce((x,e)=>x*(1-e.severity*.5),1);const availableUnits=Math.max(0,Math.min(units,supplyCapacity*disruptionFactor));const revenue=availableUnits*price;const materialCost=availableUnits*(55+w.macro.commodityIndex*.05);const laborCost=w.workforce.headcount*(35+w.workforce.wagePressure);const marketing=clamp(decision.marketing??0,0,10000);const training=clamp(decision.training??0,0,10000);const interest=w.capital.debt*(w.macro.interestRate/100)/365;const totalCosts=materialCost+laborCost+marketing+training;const cashFlow=revenue-totalCosts-interest;
 w.finance={cash:Math.max(0,w.finance.cash+cashFlow),revenue:w.finance.revenue+revenue,costs:w.finance.costs+totalCosts,grossProfit:revenue-materialCost,netCashFlow:cashFlow,debt:w.capital.debt,interestExpense:interest,valuation:0};
 const moraleDelta=(decision.hiring??0)*.1+(decision.training??0)*.001-(w.workforce.workload-60)*.08;w.workforce.headcount=clamp(w.workforce.headcount+Math.round(decision.hiring??0),1,10000);w.workforce.workload=clamp(w.workforce.workload+(w.workforce.headcount>20?2:-1));w.workforce.morale=clamp(w.workforce.morale+moraleDelta-(w.workforce.workload-60)*.03);w.workforce.productivity=clamp(w.workforce.productivity+(w.workforce.skills-60)*.015+(w.workforce.morale-60)*.02-(w.workforce.workload-70)*.04);w.workforce.retention=clamp(70+w.workforce.morale*.2-w.workforce.workload*.15);
 const satDelta=(quality-w.reputation.productQuality)*.2+(demandIndex>100?1:-1)-(availableUnits<units?2:0);w.reputation.productQuality=quality;w.reputation.service=clamp(w.reputation.service+(decision.service??0)*.02);w.reputation.employeeTreatment=clamp(w.reputation.employeeTreatment+(decision.ethics??0)*.02);w.reputation.trust=clamp(w.reputation.trust+(w.reputation.productQuality-70)*.015+(w.reputation.service-70)*.01+(w.reputation.employeeTreatment-70)*.008+satDelta*.15);
 w.customers.forEach((c,i)=>{const seg=w.segments.find(s=>s.id===c.segment)!;const fit=bounded(1-(seg.priceSensitivity*(price/100-1))*.45+(quality-70)*seg.qualitySensitivity*.006+(w.reputation.trust-50)*seg.brandSensitivity*.003,.1,1.5);const buy=bounded(.18*fit*economicDemand*seasonal*competitiveEffect);c.awareness=clamp(c.awareness+(decision.marketing??0)*.02);c.consideration=clamp(c.consideration+(c.awareness-50)*.015);c.satisfaction=clamp(c.satisfaction+satDelta*.2+(buy>.15?1:-1));c.trust=clamp(c.trust+(c.satisfaction-65)*.01);c.loyalty=clamp(c.loyalty+(c.satisfaction>70?.5:-.7));c.churnRisk=clamp(100-c.satisfaction-c.loyalty*.25);if(hash(w.seed,w.day,c.id)<buy){c.purchases++;}}
 );
 w.suppliers.forEach(s=>{s.availableCapacity=clamp(s.capacity*(1+shock(w.seed,w.day,s.id,.04)),0,s.capacity);s.unitCost=clamp(s.unitCost*(1+w.macro.inflation*.002+shock(w.seed,w.day,s.id+'cost',.01)),1,10000);s.relationship=clamp(s.relationship+(availableUnits>0?0.4:-.7));s.reliability=clamp(s.reliability-(events.some(e=>e.source===s.id)?4:0));});
 w.competitors.forEach(c=>{const perceived=Math.max(.5,Math.min(1.5,1+(price-c.price)/100*c.perceptionAccuracy));if(c.strategy==='cost_leader')c.price=clamp(price*.9*perceived,1,100000);else if(c.strategy==='premium_specialist')c.price=clamp(price*1.12,1,100000);else if(c.strategy==='fast_follower')c.price=clamp(price*.98,1,100000);else if(c.strategy==='innovator')c.quality=clamp(c.quality+.3);else if(c.strategy==='aggressive_entrant')c.price=clamp(price*.93,1,100000);c.marketShare=clamp(c.marketShare+(c.price<price?0.003:-0.001),0,.8);c.cash=Math.max(0,c.cash-c.marketing);});
 const risk=bounded((w.capital.debt/Math.max(1,w.finance.cash+w.finance.revenue*.1))*.25);w.capital.creditScore=clamp(w.capital.creditScore+(cashFlow>0?1:-1)-risk*5);w.capital.interestRate=w.macro.interestRate+Math.max(0,(70-w.capital.creditScore)*.08);w.capital.creditLimit=clamp(30000+w.capital.creditScore*1000,10000,200000);w.capital.investorConfidence=clamp(55+(w.finance.netCashFlow>0?10:-8)+(w.reputation.trust-50)*.3-risk*30);w.capital.availableCapital=Math.max(0,w.capital.creditLimit-w.capital.debt);
 const profitability=w.finance.revenue>0?w.finance.grossProfit/w.finance.revenue:0;w.finance.valuation=clamp(Math.max(1000,w.finance.revenue*.8*(1+Math.max(0,w.macro.growthRate)/20)+w.capital.investorConfidence*500)*(1-risk*.5),1000,1e12);
 effects.push({cause:'price',effect:'demand',magnitude:priceEffect,entity:'market'},{cause:'quality',effect:'customer satisfaction',magnitude:qualityEffect,entity:'customers'},{cause:'supplier capacity',effect:'available supply',magnitude:availableUnits,entity:'supply chain'},{cause:'cash flow',effect:'valuation',magnitude:profitability,entity:'business'});
 w.explanations.push({day:w.day,outcome:`Revenue ${revenue>=0?'+':''}${Math.round(revenue)}`,effects});
 return w;
}

export function validatePhase3World(w:Phase3World):string[]{const errors:string[]=[];const nums=JSON.stringify(w);if(nums.includes('NaN')||nums.includes('Infinity'))errors.push('non-finite numeric state');if(w.macro.inflation<0||w.macro.inflation>25)errors.push('inflation out of bounds');if(w.macro.interestRate<0||w.macro.interestRate>20)errors.push('interest rate out of bounds');if(w.workforce.headcount<1)errors.push('invalid headcount');if(w.finance.cash<0)errors.push('negative cash');if(w.capital.debt<0)errors.push('negative debt');if(w.customers.some(c=>c.churnRisk<0||c.churnRisk>100))errors.push('customer churn out of bounds');if(w.competitors.some(c=>c.marketShare<0||c.marketShare>.8))errors.push('competitor share out of bounds');return errors;}

export function explainPhase3Outcome(w:Phase3World):Phase3Explainability|undefined{return w.explanations[w.explanations.length-1];}
export function simulatePhase3(seed=1,days=100,decision:Phase3Decision={}):Phase3World{let w=createPhase3World(seed);for(let i=0;i<days-1;i++){w=advancePhase3World(w,decision);const errors=validatePhase3World(w);if(errors.length)throw new Error(`Phase 3 invariant violation: ${errors.join('; ')}`);}return w;}

/** Adapter for the existing simulation: runs the economic world without changing authoritative multiplayer state. */
export function advancePhase3FromSimulation(state:SimulationState, seed=state.meta?.seed??1):Phase3World{const w=createPhase3World(seed);return advancePhase3World({...w,day:Math.max(1,state.business.day),finance:{...w.finance,cash:Math.max(0,state.business.cash),revenue:Math.max(0,state.business.revenue),costs:Math.max(0,state.business.expenses),debt:Math.max(0,state.operations?.debt??0),grossProfit:0,netCashFlow:0,interestExpense:0,valuation:Math.max(1000,state.financials?.valuation??w.finance.valuation)}},{price:state.operations?.price,qualityInvestment:0,marketing:state.operations?.marketingBudget});}
