import type { SimulationChoice, SimulationState } from "@enterpriseverse/types";
import { applyChoice } from "./index";
import { advanceLivingWorldDay, getLivingWorldSummary } from "./phase26";
export type Phase4Severity="info"|"watch"|"critical";
export interface Phase4MarketPulse{economy:"boom"|"stable"|"slowdown";demand:number;confidence:number;competitivePressure:number;priceIndex:number;customerAcquisition:number;trend:"growing"|"stable"|"declining"}
export interface Phase4Health{financial:number;customers:number;operations:number;workforce:number;reputation:number;innovation:number;overall:number;risk:number}
export interface Phase4AttentionItem{id:string;severity:Phase4Severity;title:string;reason:string;metric?:string;action:string}
export interface Phase4DecisionPreview{choiceId:string;label:string;projected:{cashDelta:number;revenueDelta:number;reputationDelta:number;marketShareDelta:number;healthDelta:number;riskDelta:number}}
export interface Phase4ExecutiveBriefing{headline:string;situation:string;why:string;priorities:Array<{title:string;detail:string}>;attention:Phase4AttentionItem[];market:Phase4MarketPulse;health:Phase4Health}
export interface Phase4CommandCenter{briefing:Phase4ExecutiveBriefing;previews:Phase4DecisionPreview[];recentEvents:Array<{title:string;message:string;day:number}>;competitors:Array<{name:string;strategy:string;marketShare:number;aggression:number}>;activeScenarios:string[]}
const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v)); const round=(v:number)=>Math.round(v*10)/10; const delta=(a:number,b:number)=>round(b-a);
function financial(state:SimulationState){const cash=Math.max(0,state.business.cash),debt=Math.max(0,state.operations?.debt??state.financials?.debt??0),runway=Math.max(0,state.financials?.runwayDays??0);return round(clamp(clamp(cash/2000)*.35+(100-clamp(debt/Math.max(1,cash+debt)*100))*.35+clamp(runway/90*100)*.3));}
export function calculatePhase4MarketPulse(state:SimulationState):Phase4MarketPulse{const w=getLivingWorldSummary(state),m=state.market;return{economy:w.economy,demand:round(w.demand),confidence:round(w.confidence),competitivePressure:round(w.competitivePressure),priceIndex:round(m?.marketPrice??state.operations?.price??100),customerAcquisition:round(m?.customerAcquisition??0),trend:m?.trend??"stable"};}
export function calculatePhase4Health(state:SimulationState):Phase4Health{const o=state.operations,w=state.workforce,m=state.market,f=financial(state),trust=state.business.customers.length?state.business.customers.reduce((s,c)=>s+c.trust,0)/state.business.customers.length:50,s=clamp(o?.customerSatisfaction??50),stock=state.economy?.supplyChain?.stockoutDays??0,op=clamp(65+state.business.inventory*.3-stock*7+(o?.quality??60)*.25),wh=clamp((w?.moraleIndex??65)*.55+(w?.productivityIndex??65)*.45),rep=clamp(state.business.reputation),inn=clamp((o?.quality??60)*.65+(m?.strategyScore??50)*.35),risk=clamp(100-(f*.3+(trust*.55+s*.45)*.15+op*.15+wh*.15+rep*.1+inn*.15)),overall=clamp(f*.25+(trust*.55+s*.45)*.15+op*.15+wh*.15+rep*.1+inn*.1+(100-risk)*.1);return{financial:round(f),customers:round(clamp(trust*.55+s*.45)),operations:round(op),workforce:round(wh),reputation:round(rep),innovation:round(inn),overall:round(overall),risk:round(risk)};}
export function buildPhase4Attention(state:SimulationState):Phase4AttentionItem[]{const m=calculatePhase4MarketPulse(state),h=calculatePhase4Health(state),x:Phase4AttentionItem[]=[];if(state.business.cash<=2500||h.financial<35)x.push({id:"cash-risk",severity:"critical",title:"Cash position needs protection",reason:"Available cash or financial health is fragile.",metric:`₹${Math.round(state.business.cash).toLocaleString("en-IN")}`,action:"Review cash and funding decisions."});else if(h.financial<55)x.push({id:"cash-watch",severity:"watch",title:"Cash position is tightening",reason:"Financial headroom is shrinking.",action:"Protect liquidity."});if(m.competitivePressure>=70)x.push({id:"competition",severity:"critical",title:"Competitive pressure is high",reason:"Competitor behavior threatens market position.",metric:`${Math.round(m.competitivePressure)}/100`,action:"Review differentiation or market defense."});if(m.confidence<=40)x.push({id:"demand",severity:"critical",title:"Customer confidence is weakening",reason:"Demand conditions are becoming less predictable.",metric:`${Math.round(m.confidence)}/100`,action:"Protect demand and customer trust."});if((state.economy?.supplyChain?.stockoutDays??0)>=2)x.push({id:"supply",severity:"critical",title:"Supply chain is constraining sales",reason:"Stockouts are limiting fulfilled demand.",action:"Secure supply or adjust demand."});if(h.workforce<45)x.push({id:"workforce",severity:"critical",title:"Workforce strain is affecting execution",reason:"Morale/productivity threatens reliable delivery.",action:"Review workload and people decisions."});if(h.reputation<40)x.push({id:"reputation",severity:"critical",title:"Reputation is under pressure",reason:"Customer trust can reduce future demand.",action:"Protect customer experience."});const rank={critical:0,watch:1,info:2};return x.sort((a,b)=>rank[a.severity]-rank[b.severity]).slice(0,6);}
export function previewPhase4Decision(state:SimulationState,c:SimulationChoice):Phase4DecisionPreview{const before=calculatePhase4Health(state),after=calculatePhase4Health(applyChoice(state,c));return{choiceId:c.id,label:c.label,projected:{cashDelta:round(c.effects.cash??0),revenueDelta:round(c.effects.revenue??0),reputationDelta:round(c.effects.reputation??0),marketShareDelta:round(c.effects.marketShare??0),healthDelta:delta(before.overall,after.overall),riskDelta:delta(before.risk,after.risk)}};}
export function buildPhase4ExecutiveBriefing(state:SimulationState):Phase4ExecutiveBriefing{const market=calculatePhase4MarketPulse(state),health=calculatePhase4Health(state),attention=buildPhase4Attention(state);return{headline:attention[0]?.title??"The enterprise is stable, but the next decision matters",situation:`Day ${state.business.day}: ${state.business.name} is facing a ${market.economy} economy with ${Math.round(market.demand)}/100 demand and ${Math.round(market.competitivePressure)}/100 competitive pressure.`,why:market.trend==="growing"?"Demand is improving; capacity, pricing and retention matter.":market.trend==="declining"?"Demand is weakening; cash discipline and customer value matter.":"Market conditions are mixed; preserve optionality while fixing bottlenecks.",priorities:[{title:"Protect the constraint",detail:attention[0]?.action??"Review the latest signals."},{title:"Read the market",detail:`${market.trend} demand with ${Math.round(market.confidence)}/100 confidence.`},{title:"Keep execution healthy",detail:`Overall health ${Math.round(health.overall)}/100; risk ${Math.round(health.risk)}/100.`}],attention,market,health};}
export function getPhase4CommandCenter(state:SimulationState,choices:SimulationChoice[]=[]):Phase4CommandCenter{const briefing=buildPhase4ExecutiveBriefing(state);return{briefing,previews:choices.map(c=>previewPhase4Decision(state,c)),recentEvents:(state.events??[]).slice(0,5).map(e=>({title:e.title,message:e.message,day:e.day})),competitors:[...(state.agents?.competitors??[])].sort((a,b)=>b.marketShare-a.marketShare).slice(0,5).map(c=>({name:c.name,strategy:c.strategy,marketShare:round(c.marketShare),aggression:round(c.aggression)})),activeScenarios:(state.scenarios?.active??[]).map(s=>s.title)};}
export const resolveChoice=(state:SimulationState,c:SimulationChoice)=>applyChoice(state,c);
export const advancePhase4Day=(state:SimulationState)=>advanceLivingWorldDay(state);
