export type Skill23 = "finance" | "strategy" | "operations" | "marketing" | "leadership" | "risk" | "customer" | "innovation" | "ethics";
export type ScenarioCategory23 = "finance" | "market" | "operations" | "people" | "strategy" | "resilience" | "ethics";
export type ScenarioDifficulty23 = "foundation" | "developing" | "advanced" | "expert" | "founder";
export type ChoiceQuality23 = "excellent" | "strong" | "mixed" | "weak" | "dangerous";

export interface ScenarioChoice23 { id:string; label:string; description:string; skills:Partial<Record<Skill23,number>>; risk:number; cashEffect:number; reputationEffect:number; customerEffect:number; strategicEffect:number; delayedEffect:number; }
export interface Scenario23 { id:string; category:ScenarioCategory23; difficulty:ScenarioDifficulty23; title:string; situation:string; whyItMatters:string; skills:Skill23[]; choices:ScenarioChoice23[]; lesson:string; tags:string[]; }
export interface SkillProfile23 { skills:Record<Skill23,number>; strongest:Skill23[]; weakest:Skill23[]; totalDecisions:number; confidence:number; }
export interface DecisionEvaluation23 { scenarioId:string; choiceId:string; quality:ChoiceQuality23; score:number; immediateImpact:number; delayedImpact:number; tradeoffBalance:number; skillAlignment:number; riskDiscipline:number; explanation:string; lesson:string; }
export interface LearningRecord23 { scenarioId:string; day:number; category:ScenarioCategory23; skills:Skill23[]; score:number; quality:ChoiceQuality23; lesson:string; }
export interface Phase23Challenge23 { scenario:Scenario23; reason:"weak_skill"|"recent_failure"|"progression"|"variety"|"replay"; targetSkills:Skill23[]; seed:number; }
export interface Phase23Debrief23 { score:number; founderStyle:string; strengths:string[]; blindSpots:string[]; lessons:string[]; nextChallenge:string; decisionCount:number; }

const SKILLS:Skill23[]=["finance","strategy","operations","marketing","leadership","risk","customer","innovation","ethics"];
const clamp=(n:number,min=0,max=100)=>Math.max(min,Math.min(max,n));
const round=(n:number)=>Math.round(n*100)/100;
function hash(input:string){let h=2166136261;for(let i=0;i<input.length;i+=1)h=Math.imul(h^input.charCodeAt(i),16777619);return h>>>0;}
function rand(seed:number,salt:number){let x=(seed^Math.imul(salt+1,0x9e3779b9))>>>0;x^=x<<13;x^=x>>>17;x^=x<<5;return((x>>>0)%1000003)/1000003;}
function emptySkills():Record<Skill23,number>{return{finance:50,strategy:50,operations:50,marketing:50,leadership:50,risk:50,customer:50,innovation:50,ethics:50};}

const SCENARIOS:Scenario23[]=[
{id:"cash-runway-23",category:"finance",difficulty:"developing",title:"The runway decision",situation:"Cash is tightening while a growth opportunity appears. Taking it could accelerate revenue, but it reduces your safety buffer.",whyItMatters:"Growth without liquidity can destroy an otherwise healthy business.",skills:["finance","risk","strategy"],lesson:"Protect survival while investing selectively; the best answer is rarely the biggest possible bet.",tags:["cash","growth"],choices:[{id:"bet-big",label:"Bet aggressively",description:"Commit most available cash.",skills:{strategy:70,risk:25,finance:20},risk:90,cashEffect:-45,reputationEffect:2,customerEffect:8,strategicEffect:12,delayedEffect:15},{id:"stage",label:"Stage the investment",description:"Test first, then scale on evidence.",skills:{finance:80,risk:85,strategy:82},risk:35,cashEffect:-15,reputationEffect:2,customerEffect:5,strategicEffect:10,delayedEffect:12},{id:"protect",label:"Protect cash",description:"Preserve runway for the core business.",skills:{finance:65,risk:78},risk:20,cashEffect:2,reputationEffect:0,customerEffect:-3,strategicEffect:-4,delayedEffect:-5}]},
{id:"price-war-23",category:"market",difficulty:"advanced",title:"A competitor starts a price war",situation:"Your strongest competitor cuts price by 18%. Matching would compress your margin sharply.",whyItMatters:"Price is only one part of competitive positioning.",skills:["strategy","customer","finance","marketing"],lesson:"Compete on the dimension that creates durable value instead of automatically copying a competitor.",tags:["competition","pricing"],choices:[{id:"match",label:"Match immediately",description:"Cut your price by the same amount.",skills:{finance:30,strategy:45,customer:65},risk:70,cashEffect:-8,reputationEffect:0,customerEffect:10,strategicEffect:3,delayedEffect:-12},{id:"differentiate",label:"Differentiate the offer",description:"Strengthen the value customers care about most.",skills:{strategy:88,marketing:82,customer:90},risk:35,cashEffect:-6,reputationEffect:8,customerEffect:7,strategicEffect:15,delayedEffect:14},{id:"premium",label:"Raise price and prove value",description:"Move upmarket with stronger positioning.",skills:{marketing:78,strategy:80,risk:55},risk:58,cashEffect:4,reputationEffect:6,customerEffect:-4,strategicEffect:12,delayedEffect:10}]},
{id:"supplier-shock-23",category:"operations",difficulty:"advanced",title:"Your supplier becomes unreliable",situation:"Your primary supplier has missed deliveries twice. Switching costs more, but staying creates serious stockout risk.",whyItMatters:"Resilience looks expensive until a disruption arrives.",skills:["operations","risk","finance"],lesson:"Diversification and contingency capacity reduce future shock costs.",tags:["supply","resilience"],choices:[{id:"stay",label:"Stay with the supplier",description:"Accept the risk because it is cheaper.",skills:{finance:55,risk:25,operations:45},risk:82,cashEffect:5,reputationEffect:-5,customerEffect:-8,strategicEffect:-4,delayedEffect:-15},{id:"dual",label:"Build a second source",description:"Qualify a reliable backup while keeping the relationship.",skills:{operations:90,risk:92,finance:75},risk:25,cashEffect:-8,reputationEffect:4,customerEffect:3,strategicEffect:12,delayedEffect:18},{id:"switch",label:"Switch completely",description:"Move immediately to a more reliable supplier.",skills:{operations:78,risk:70},risk:45,cashEffect:-15,reputationEffect:3,customerEffect:5,strategicEffect:8,delayedEffect:9}]},
{id:"team-conflict-23",category:"people",difficulty:"developing",title:"A high performer is damaging the team",situation:"A talented employee delivers excellent results but is creating conflict and lowering collaboration.",whyItMatters:"Leadership decisions affect performance through people.",skills:["leadership","risk","strategy"],lesson:"High individual performance cannot compensate indefinitely for a broken team system.",tags:["people","culture"],choices:[{id:"ignore",label:"Ignore it",description:"Keep the employee for individual output.",skills:{leadership:20},risk:80,cashEffect:2,reputationEffect:-8,customerEffect:-5,strategicEffect:-4,delayedEffect:-14},{id:"coach",label:"Coach and reset expectations",description:"Set standards and give a path to improve.",skills:{leadership:92,risk:72,strategy:70},risk:28,cashEffect:-2,reputationEffect:8,customerEffect:5,strategicEffect:10,delayedEffect:16},{id:"replace",label:"Replace the employee",description:"Accept short-term disruption to protect culture.",skills:{leadership:70,risk:65},risk:48,cashEffect:-12,reputationEffect:3,customerEffect:2,strategicEffect:7,delayedEffect:8}]},
{id:"ethical-growth-23",category:"ethics",difficulty:"expert",title:"Fast growth with a hidden cost",situation:"A marketing channel can increase acquisition quickly, but relies on practices that reduce transparency.",whyItMatters:"Short-term growth can create long-term trust and reputation costs.",skills:["ethics","marketing","risk","leadership"],lesson:"Sustainable growth includes the cost of trust.",tags:["ethics","trust"],choices:[{id:"use",label:"Use the channel",description:"Prioritize acquisition and accept the trade-off.",skills:{marketing:75,risk:20},risk:88,cashEffect:14,reputationEffect:-18,customerEffect:12,strategicEffect:8,delayedEffect:-24},{id:"redesign",label:"Redesign the campaign",description:"Keep the growth goal without misleading elements.",skills:{ethics:95,marketing:82,risk:90},risk:25,cashEffect:5,reputationEffect:12,customerEffect:8,strategicEffect:13,delayedEffect:20},{id:"reject",label:"Reject it",description:"Walk away from the channel.",skills:{ethics:92,risk:88},risk:15,cashEffect:-4,reputationEffect:10,customerEffect:-2,strategicEffect:3,delayedEffect:9}]},
{id:"innovation-moat-23",category:"strategy",difficulty:"expert",title:"Build the moat or harvest the cash",situation:"Your product is performing well. Harvest current success or reinvest in a capability competitors cannot easily copy.",whyItMatters:"Strong businesses balance current performance with future defensibility.",skills:["innovation","strategy","finance","risk"],lesson:"A moat is built before you urgently need one.",tags:["innovation","moat"],choices:[{id:"harvest",label:"Harvest the cash",description:"Maximize current profit.",skills:{finance:75},risk:35,cashEffect:15,reputationEffect:0,customerEffect:2,strategicEffect:-4,delayedEffect:-12},{id:"moat",label:"Build a defensible capability",description:"Invest in long-term differentiation.",skills:{innovation:94,strategy:90,finance:72},risk:42,cashEffect:-18,reputationEffect:8,customerEffect:10,strategicEffect:20,delayedEffect:24},{id:"split",label:"Split the capital",description:"Maintain the engine while funding focused innovation.",skills:{finance:82,innovation:82,strategy:85},risk:28,cashEffect:-8,reputationEffect:5,customerEffect:7,strategicEffect:15,delayedEffect:18}]}
];

export function getPhase23Scenarios():Scenario23[]{return SCENARIOS.map(s=>({...s,choices:s.choices.map(c=>({...c,skills:{...c.skills}}))}));}
export function createSkillProfile23(records:LearningRecord23[]=[]):SkillProfile23{const skills=emptySkills();for(const r of records){const gain=(r.score-50)/12;for(const k of r.skills)skills[k]=clamp(skills[k]+gain*.35);}const strongest=[...SKILLS].sort((a,b)=>skills[b]-skills[a]).slice(0,3);const weakest=[...SKILLS].sort((a,b)=>skills[a]-skills[b]).slice(0,3);return{skills:Object.fromEntries(SKILLS.map(k=>[k,round(skills[k])])) as Record<Skill23,number>,strongest,weakest,totalDecisions:records.length,confidence:clamp(45+Math.min(40,records.length*2))};}
export function evaluatePhase23Decision(scenario:Scenario23,choiceId:string,profile:SkillProfile23,context:{cash?:number;reputation?:number;marketPressure?:number}={}):DecisionEvaluation23{const c=scenario.choices.find(x=>x.id===choiceId);if(!c)throw new Error(`Unknown Phase 23 choice: ${choiceId}`);const vals=Object.entries(c.skills).map(([k,w])=>(profile.skills[k as Skill23]/100)*(w??0));const alignment=clamp(vals.reduce((a,b)=>a+b,0)/Math.max(1,Object.keys(c.skills).length));const cash=context.cash??50000,reputation=context.reputation??60,pressure=context.marketPressure??50;const riskPenalty=Math.max(0,c.risk-profile.skills.risk)*.8+(cash<10000&&c.cashEffect<-20?22:0)+(reputation<35&&c.reputationEffect<0?15:0)+(pressure>70&&c.risk>70?10:0);const immediate=clamp(50+c.cashEffect*.8+c.reputationEffect*1.2+c.customerEffect*.8);const delayed=clamp(50+c.delayedEffect*2+c.strategicEffect*.8);const tradeoff=clamp(75-Math.abs(c.cashEffect)*.5-Math.abs(c.risk-45)*.25+c.strategicEffect*.35);const discipline=clamp(100-riskPenalty);const score=round(clamp(immediate*.22+delayed*.30+tradeoff*.18+alignment*.18+discipline*.12));const quality:ChoiceQuality23=score>=85?"excellent":score>=72?"strong":score>=55?"mixed":score>=38?"weak":"dangerous";const explanation=quality==="excellent"?"This balances survival, strategic value and risk discipline.":quality==="strong"?"This is strategically sound, with one meaningful trade-off remaining.":quality==="mixed"?"This can work, but a material weakness or delayed consequence remains.":quality==="weak"?"The immediate benefit carries more strategic or risk cost than the situation justifies.":"This creates unusually high downside relative to the available evidence and resilience.";return{scenarioId:scenario.id,choiceId,quality,score,immediateImpact:round(immediate),delayedImpact:round(delayed),tradeoffBalance:round(tradeoff),skillAlignment:round(alignment),riskDiscipline:round(discipline),explanation,lesson:scenario.lesson};}
export function generatePhase23Challenge(seedInput:number|string,profile:SkillProfile23,history:LearningRecord23[]=[]):Phase23Challenge23{const seed=typeof seedInput==="number"?Math.abs(Math.floor(seedInput))>>>0:hash(seedInput);const recent=history.slice(-3);const average=recent.length?recent.reduce((s,r)=>s+r.score,0)/recent.length:100;const reason:Phase23Challenge23["reason"]=average<58?"recent_failure":profile.totalDecisions<3?"progression":"weak_skill";const targets=reason==="weak_skill"||reason==="recent_failure"?profile.weakest.slice(0,2):[SKILLS[Math.floor(rand(seed,history.length+7)*SKILLS.length)]];const pool=SCENARIOS.filter(s=>s.skills.some(k=>targets.includes(k)));const candidates=pool.length?pool:SCENARIOS;const ranked=candidates.map(s=>({s,score:s.skills.filter(k=>targets.includes(k)).length*30+(history.at(-1)?.category===s.category?-12:0)+rand(seed,s.id.length)*10})).sort((a,b)=>b.score-a.score);return{scenario:ranked[0].s,reason,targetSkills:targets,seed};}
export function recordPhase23Learning(history:LearningRecord23[],evaluation:DecisionEvaluation23,day:number,category:ScenarioCategory23,skills:Skill23[]):LearningRecord23[]{return[...history,{scenarioId:evaluation.scenarioId,day,category,skills:[...skills],score:evaluation.score,quality:evaluation.quality,lesson:evaluation.lesson}].slice(-200);}
export function createPhase23Debrief(history:LearningRecord23[],profile=createSkillProfile23(history)):Phase23Debrief23{const score=round(history.length?history.reduce((s,r)=>s+r.score,0)/history.length:0);const strengths=profile.strongest.map(k=>`${k} — demonstrated consistently across your decisions.`);const blindSpots=profile.weakest.map(k=>`${k} — a useful focus area for your next decisions.`);const lessons=[...new Set(history.slice(-8).map(r=>r.lesson))].slice(-3);const founderStyle=profile.strongest.includes("strategy")&&profile.strongest.includes("risk")?"Strategic Risk Manager":profile.strongest.includes("innovation")?"Innovative Builder":profile.strongest.includes("customer")?"Customer-Led Founder":profile.strongest.includes("finance")?"Capital Disciplined Founder":"Adaptive Generalist";return{score,founderStyle,strengths,blindSpots,lessons,nextChallenge:`Practice ${profile.weakest[0]??"a new skill"} in a scenario where the trade-off is deliberately difficult.`,decisionCount:history.length};}
export function phase23Signature(challenge:Phase23Challenge23,history:LearningRecord23[]):string{return String(hash(JSON.stringify({seed:challenge.seed,scenario:challenge.scenario.id,reason:challenge.reason,history:history.slice(-20).map(r=>[r.scenarioId,r.score,r.quality])})));}
export function recommendPhase23Scenarios(profile:SkillProfile23,count=3):Scenario23[]{const safe=Math.max(1,Math.min(5,Math.floor(count)));return[...SCENARIOS].sort((a,b)=>b.skills.reduce((s,k)=>s+(100-profile.skills[k]),0)-a.skills.reduce((s,k)=>s+(100-profile.skills[k]),0)).slice(0,safe);}
