import type { Phase16Difficulty, Phase16Run } from "./phase16";

export type CompetitionStatus = "lobby" | "active" | "completed" | "cancelled";
export type CompetitionType = "quick_match" | "friends_only" | "private" | "classroom";
export type RatingTier = "bronze" | "silver" | "gold" | "platinum" | "diamond" | "master";

export interface CompetitionPlayer17 { id: string; displayName: string; ready: boolean; connected: boolean; score: number; marketShare: number; reputation: number; completedDays: number; rating: number; result?: "win" | "loss" | "draw"; }
export interface CompetitionRoom17 { id: string; code: string; hostId: string; type: CompetitionType; status: CompetitionStatus; maxPlayers: number; difficulty: Phase16Difficulty; worldSeed: number; durationDays: number; currentDay: number; players: CompetitionPlayer17[]; createdAt: string; }
export interface DecisionSubmission17 { playerId: string; day: number; decisionId: string; submittedAt: string; }
export interface VerifiedRun17 { runId: string; roomId: string; playerId: string; worldSeed: number; simulationVersion: string; decisions: DecisionSubmission17[]; finalScore: number; completedAt: string; verificationHash: string; }
export interface LeaderboardEntry17 { playerId: string; displayName: string; rating: number; tier: RatingTier; score: number; wins: number; games: number; verified: boolean; }

const clamp = (n: number, min = 0, max = 100) => Math.max(min, Math.min(max, n));
const stableHash = (value: string): string => { let h1 = 0x811c9dc5; let h2 = 0x01000193; for (let i = 0; i < value.length; i += 1) { h1 = Math.imul(h1 ^ value.charCodeAt(i), 16777619); h2 = Math.imul(h2 ^ value.charCodeAt(i), 2246822519); } return `${(h1 >>> 0).toString(16).padStart(8, "0")}${(h2 >>> 0).toString(16).padStart(8, "0")}`; };

export function ratingTier17(rating: number): RatingTier { if (rating >= 1800) return "master"; if (rating >= 1600) return "diamond"; if (rating >= 1400) return "platinum"; if (rating >= 1200) return "gold"; if (rating >= 1000) return "silver"; return "bronze"; }
export function createCompetitionRoom17(input: { id: string; code: string; hostId: string; type?: CompetitionType; maxPlayers?: number; difficulty?: Phase16Difficulty; worldSeed: number; durationDays?: number; createdAt?: string }): CompetitionRoom17 { const maxPlayers = Math.round(clamp(Math.floor(input.maxPlayers ?? 4), 2, 8)); const durationDays = Math.round(clamp(Math.floor(input.durationDays ?? 30), 5, 90)); return { id: input.id, code: input.code.trim().toUpperCase(), hostId: input.hostId, type: input.type ?? "friends_only", status: "lobby", maxPlayers, difficulty: input.difficulty ?? "standard", worldSeed: Math.abs(Math.floor(input.worldSeed)) >>> 0, durationDays, currentDay: 1, players: [], createdAt: input.createdAt ?? new Date().toISOString() }; }
export function addCompetitionPlayer17(room: CompetitionRoom17, player: CompetitionPlayer17): CompetitionRoom17 { if (room.status !== "lobby") throw new Error("Players can only join a lobby."); if (room.players.some((p) => p.id === player.id)) return room; if (room.players.length >= room.maxPlayers) throw new Error("Competition room is full."); return { ...room, players: [...room.players, { ...player, score: clamp(player.score), marketShare: clamp(player.marketShare), reputation: clamp(player.reputation) }] }; }
export function setCompetitionReady17(room: CompetitionRoom17, playerId: string, ready: boolean): CompetitionRoom17 { if (!room.players.some((p) => p.id === playerId)) throw new Error("Player is not in this room."); return { ...room, players: room.players.map((p) => p.id === playerId ? { ...p, ready } : p) }; }
export function canStartCompetition17(room: CompetitionRoom17): boolean { return room.status === "lobby" && room.players.length >= 2 && room.players.every((player) => player.ready); }
export function startCompetition17(room: CompetitionRoom17): CompetitionRoom17 { if (!canStartCompetition17(room)) throw new Error("Competition cannot start until at least two players are ready."); return { ...room, status: "active", currentDay: 1 }; }
export function submitDecision17(submissions: DecisionSubmission17[], submission: DecisionSubmission17): DecisionSubmission17[] { if (submission.day < 1) throw new Error("Decision day must be positive."); return [...submissions.filter((item) => !(item.playerId === submission.playerId && item.day === submission.day)), submission]; }
export function allPlayersSubmitted17(room: CompetitionRoom17, submissions: DecisionSubmission17[], day = room.currentDay): boolean { return room.players.length >= 2 && room.players.every((player) => submissions.some((item) => item.playerId === player.id && item.day === day)); }
export function advanceCompetitionDay17(room: CompetitionRoom17, submissions: DecisionSubmission17[]): CompetitionRoom17 { if (room.status !== "active") throw new Error("Only an active competition can advance."); if (!allPlayersSubmitted17(room, submissions)) throw new Error("Every player must submit a decision before the round resolves."); return room.currentDay >= room.durationDays ? { ...room, status: "completed" } : { ...room, currentDay: room.currentDay + 1 }; }
export function calculateCompetitiveScore17(run: Phase16Run): number { const s = run.state; const cash = clamp(s.business.cash / 1000); const revenue = clamp(s.business.revenue / 2500); const reputation = clamp(s.business.reputation); const share = clamp(s.business.marketShare * 4); const satisfaction = clamp(s.operations?.customerSatisfaction ?? 50); const profit = clamp(((s.financials?.netProfit ?? 0) + Math.max(0, s.financials?.cash ?? s.business.cash)) / 700); return Math.round((cash * .2 + revenue * .15 + reputation * .2 + share * .15 + satisfaction * .15 + profit * .15) * 100) / 100; }
export function verifyRun17(run: Phase16Run, input: { runId: string; roomId: string; playerId: string; decisions: DecisionSubmission17[]; simulationVersion?: string; completedAt?: string }): VerifiedRun17 { const finalScore = calculateCompetitiveScore17(run); const completedAt = input.completedAt ?? new Date().toISOString(); const simulationVersion = input.simulationVersion ?? "phase-17"; const canonical = JSON.stringify({ runId: input.runId, roomId: input.roomId, playerId: input.playerId, worldSeed: run.seed, simulationVersion, decisions: input.decisions, finalScore, completedAt }); return { runId: input.runId, roomId: input.roomId, playerId: input.playerId, worldSeed: run.seed, simulationVersion, decisions: [...input.decisions], finalScore, completedAt, verificationHash: stableHash(canonical) }; }
export function rankCompetition17(players: CompetitionPlayer17[]): CompetitionPlayer17[] { const sorted = [...players].sort((a, b) => b.score - a.score || b.marketShare - a.marketShare || b.reputation - a.reputation || a.id.localeCompare(b.id)); const top = sorted[0]; return sorted.map((player, index) => ({ ...player, result: index === 0 ? "win" : top && player.score === top.score && player.marketShare === top.marketShare && player.reputation === top.reputation ? "draw" : "loss" })); }
export function calculateElo17(playerRating: number, opponentRating: number, actual: number, k = 32): number { const expected = 1 / (1 + 10 ** ((opponentRating - playerRating) / 400)); return Math.round(playerRating + k * (actual - expected)); }
export function createLeaderboardEntry17(input: { playerId: string; displayName: string; rating?: number; score: number; wins?: number; games?: number; verified?: boolean }): LeaderboardEntry17 { const rating = Math.max(0, Math.round(input.rating ?? 1000)); return { playerId: input.playerId, displayName: input.displayName, rating, tier: ratingTier17(rating), score: clamp(input.score), wins: Math.max(0, Math.floor(input.wins ?? 0)), games: Math.max(0, Math.floor(input.games ?? 0)), verified: Boolean(input.verified) }; }
export function compareRuns17(a: Phase16Run, b: Phase16Run): { first: number; second: number; winner: "first" | "second" | "draw" } { const first = calculateCompetitiveScore17(a); const second = calculateCompetitiveScore17(b); return { first, second, winner: first === second ? "draw" : first > second ? "first" : "second" }; }
