import { describe, expect, it } from "vitest";
import { addCompetitionPlayer17, advanceCompetitionDay17, calculateElo17, canStartCompetition17, createCompetitionRoom17, createLeaderboardEntry17, rankCompetition17, setCompetitionReady17, startCompetition17, submitDecision17, ratingTier17 } from "./phase17";

const player = (id: string) => ({ id, displayName: id, ready: false, connected: true, score: 50, marketShare: 10, reputation: 60, completedDays: 0, rating: 1000 });

describe("Phase 17 multiplayer competition", () => {
  it("creates a bounded lobby", () => { const room = createCompetitionRoom17({ id: "r1", code: "abc123", hostId: "a", worldSeed: 42, maxPlayers: 99 }); expect(room.code).toBe("ABC123"); expect(room.maxPlayers).toBe(8); expect(room.status).toBe("lobby"); });
  it("requires two ready players", () => { let room = createCompetitionRoom17({ id: "r1", code: "ABC", hostId: "a", worldSeed: 1 }); room = addCompetitionPlayer17(room, player("a")); room = addCompetitionPlayer17(room, player("b")); expect(canStartCompetition17(room)).toBe(false); room = setCompetitionReady17(room, "a", true); room = setCompetitionReady17(room, "b", true); expect(canStartCompetition17(room)).toBe(true); expect(startCompetition17(room).status).toBe("active"); });
  it("resolves a synchronized round", () => { let room = createCompetitionRoom17({ id: "r1", code: "ABC", hostId: "a", worldSeed: 1, durationDays: 2 }); room = addCompetitionPlayer17(room, player("a")); room = addCompetitionPlayer17(room, player("b")); room = setCompetitionReady17(setCompetitionReady17(room, "a", true), "b", true); room = startCompetition17(room); let submissions = submitDecision17([], { playerId: "a", day: 1, decisionId: "x", submittedAt: "t" }); submissions = submitDecision17(submissions, { playerId: "b", day: 1, decisionId: "y", submittedAt: "t" }); expect(advanceCompetitionDay17(room, submissions).currentDay).toBe(2); });
  it("prevents incomplete rounds", () => { let room = createCompetitionRoom17({ id: "r1", code: "ABC", hostId: "a", worldSeed: 1 }); room = addCompetitionPlayer17(room, player("a")); room = addCompetitionPlayer17(room, player("b")); room = setCompetitionReady17(setCompetitionReady17(room, "a", true), "b", true); room = startCompetition17(room); expect(() => advanceCompetitionDay17(room, [{ playerId: "a", day: 1, decisionId: "x", submittedAt: "t" }])).toThrow(); });
  it("assigns deterministic leaderboard ranks and rating tiers", () => { const ranked = rankCompetition17([{ ...player("a"), score: 90 }, { ...player("b"), score: 90, marketShare: 12 }, { ...player("c"), score: 70 }]); expect(ranked.map((p) => p.id)).toEqual(["b", "a", "c"]); expect(ranked[0].result).toBe("win"); expect(ranked[1].result).toBe("loss"); expect(ratingTier17(1500)).toBe("platinum"); expect(createLeaderboardEntry17({ playerId: "a", displayName: "A", score: 91, rating: 1500, verified: true }).verified).toBe(true); });
  it("calculates bounded Elo-style updates", () => { expect(calculateElo17(1000, 1000, 1)).toBe(1016); expect(calculateElo17(1000, 1000, 0)).toBe(984); });
});
