"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { applyChoice, assessLearning, buildDecisionDebrief, calculateKpis, getFounderProgress } from "@enterpriseverse/simulation";
import type { SimulationChoice, SimulationState } from "@enterpriseverse/types";
import { useSimulation } from "../lib/simulation/useSimulation";
import CanonicalShell from "../experience/CanonicalShell";
import "./day1.css";

const money = (value: number) => `₹${Math.round(value).toLocaleString("en-IN")}`;
function Delta({ label, before, after, format = "number" }: { label: string; before: number; after: number; format?: "number" | "money" | "percent" }) { const delta = after - before; const value = format === "money" ? money(Math.abs(delta)) : format === "percent" ? `${Math.abs(delta).toFixed(1)}%` : Math.abs(delta).toFixed(1); return <div className={delta >= 0 ? "ev-delta positive" : "ev-delta negative"}><small>{label}</small><strong>{delta >= 0 ? "+" : "−"}{value}</strong></div>; }
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="ev-cockpit-metric"><small>{label}</small><strong>{value}</strong><span>{detail}</span></div>; }

export default function Day1Page() {
  const { state, status, error, commitChoice, endDay } = useSimulation();
  const [selected, setSelected] = useState<string | null>(null);
  const [consequence, setConsequence] = useState<{ before: SimulationState; after: SimulationState; choice: SimulationChoice } | null>(null);
  const [showWhatIf, setShowWhatIf] = useState(false);
  useEffect(() => { if (status === "ready" && !state) window.location.assign("/founder"); }, [state, status]);
  const event = state?.events?.[0]; const kpis = state ? calculateKpis(state) : null; const progress = state ? getFounderProgress(state) : null; const learning = state ? assessLearning(state) : null; const chosen = event?.choices.find((item) => item.id === selected) ?? null; const preview = state && chosen ? applyChoice(state, chosen) : null; const debrief = state && chosen ? buildDecisionDebrief(state, chosen) : null; const committed = consequence?.choice ?? null; const committedDebrief = consequence ? buildDecisionDebrief(consequence.before, consequence.choice) : null; const decisionOptions = useMemo(() => event?.choices ?? [], [event]);
  if (!state || !kpis || !progress || !learning) return <main className="ev-day-loading"><span className="ev-live-pulse" /><p>{status === "error" ? error : "Loading your enterprise…"}</p><Link href="/founder">Founder setup</Link></main>;
  const commit = async () => { if (!chosen) return; const before = state; const after = await commitChoice(chosen); if (after) { setConsequence({ before, after, choice: chosen }); setSelected(null); setShowWhatIf(false); window.setTimeout(() => document.getElementById("consequence")?.scrollIntoView({ behavior: "smooth", block: "start" }), 50); } };
  const continueDay = async () => { setConsequence(null); await endDay(); window.scrollTo({ top: 0, behavior: "smooth" }); };
  return <CanonicalShell state={state}>
    <div className="ev-day-header"><div><span className="ev-kicker">ENTERPRISE · CEO COCKPIT · DAY {state.business.day}</span><h1>{state.business.name}</h1><p>{state.business.idea}</p></div><div className="ev-save-state" role="status" aria-live="polite"><span className={status === "saving" ? "saving" : "saved"} />{status === "saving" ? "Saving…" : status === "error" ? "Local save preserved" : "Saved"}</div></div>
    <section id="ev-attention" className="ev-attention-banner"><div><span className="ev-kicker">WHAT NEEDS YOUR ATTENTION</span><h2>{event ? event.title : "The world is waiting for your next move."}</h2><p>{event ? event.message : "Advance the day to reveal the next market signal."}</p></div><span className="ev-attention-badge">{event ? "DECISION" : "READY"}</span></section>
    <section className="ev-cockpit"><div className="ev-section-title"><div><span className="ev-kicker">CEO COCKPIT</span><h2>What changed. Why it matters. What you can do.</h2></div><span className="ev-cockpit-health">{progress.health.toUpperCase()}</span></div><div className="ev-metric-grid"><Metric label="CASH" value={money(state.business.cash)} detail={`${kpis.cashRunwayDays} days runway`} /><Metric label="REVENUE" value={money(state.business.revenue)} detail={`${kpis.grossMargin}% gross margin`} /><Metric label="CUSTOMERS" value={`${state.business.customers.length}`} detail={`${kpis.customerSatisfaction}% satisfaction`} /><Metric label="MARKET SHARE" value={`${state.business.marketShare.toFixed(1)}%`} detail={`Demand ${state.market.demandIndex}`} /><Metric label="REPUTATION" value={`${Math.round(state.business.reputation)}/100`} detail="Customer trust" /></div><div className="ev-cockpit-grid"><article><span className="ev-kicker">WHY IT MATTERS</span><h3>{event ? "A decision is now part of the company's reality." : "Keep strengthening the enterprise."}</h3><p>{event ? "The simulation has created a situation that connects market conditions to your business. Compare the options instead of looking for a perfect answer." : "Use the next day to observe how the market, operations and customers respond to your previous choices."}</p></article><article><span className="ev-kicker">FOUNDER SIGNAL</span><h3>{progress.health === "excellent" ? "You have room to take calculated risk." : "Protect the fundamentals before expanding risk."}</h3><p>{progress.level > 1 ? `Founder level ${progress.level} · ${progress.xp} XP earned from actual simulation behavior.` : "Your founder journey starts with this first decision."}</p></article></div></section>
    {event && !consequence && <section id="decision" className="ev-decision-theater"><div className="ev-theater-header"><span className="ev-kicker">DECISION THEATER · {event.choices.length} OPTIONS</span><h2>{event.title}</h2><p>{event.message}</p></div><div className="ev-decision-flow"><span className="active">SITUATION</span><i>→</i><span>TRADE-OFFS</span><i>→</i><span>WHAT-IF</span><i>→</i><span>COMMIT</span></div><div className="ev-option-grid">{decisionOptions.map((choice) => { const active = selected === choice.id; const risk = Object.values(choice.effects).some((value) => value < -10) ? "HIGH" : Object.values(choice.effects).some((value) => value < 0) ? "MEDIUM" : "LOW"; return <button key={choice.id} type="button" className={`ev-option ${active ? "selected" : ""}`} aria-pressed={active} onClick={() => setSelected(choice.id)}><span className="ev-option-top"><small>OPTION</small><b>{risk} RISK</b></span><strong>{choice.label}</strong><p>Commit this move and let the simulation calculate its consequences.</p><div className="ev-effect-list">{Object.entries(choice.effects).slice(0, 4).map(([label, value]) => <span key={label}><small>{label}</small><b>{value >= 0 ? "+" : ""}{value}</b></span>)}</div></button>; })}</div>{chosen && preview && <section className="ev-whatif"><button type="button" className="ev-whatif-toggle" aria-expanded={showWhatIf} onClick={() => setShowWhatIf((v) => !v)}><span><b>WHAT-IF</b><small>Preview this decision before committing</small></span><span>{showWhatIf ? "−" : "+"}</span></button>{showWhatIf && <div className="ev-whatif-panel"><p>Projection only. Your company changes only when you commit.</p><div className="ev-delta-grid"><Delta label="Cash" before={state.business.cash} after={preview.business.cash} format="money" /><Delta label="Revenue" before={state.business.revenue} after={preview.business.revenue} format="money" /><Delta label="Market share" before={state.business.marketShare} after={preview.business.marketShare} format="percent" /><Delta label="Reputation" before={state.business.reputation} after={preview.business.reputation} /></div>{debrief && <div className="ev-tradeoff"><span>TRADE-OFF</span><strong>{debrief.lesson}</strong><small>The simulation does not reveal a correct answer. The choice changes the state you will have to manage next.</small></div>}</div>}</section>}<div className="ev-theater-commit"><span>{chosen ? `Selected: ${chosen.label}` : "Select an option to continue."}</span><button type="button" className="ev-primary" disabled={!chosen || status === "saving"} onClick={() => void commit()}>{status === "saving" ? "Committing…" : "Commit decision →"}</button></div></section>}
    {consequence && committed && committedDebrief && <section id="consequence" className="ev-consequence"><div className="ev-kicker">CONSEQUENCE · DAY {consequence.after.business.day}</div><h2>You made the call.</h2><p className="ev-consequence-choice">“{committed.label}”</p><div className="ev-causal-chain"><div><small>YOUR DECISION</small><strong>{committed.label}</strong></div><i>↓</i><div><small>BUSINESS RESPONSE</small><strong>Simulation state updated</strong><span>Cash, revenue, reputation and operations recalculated.</span></div><i>↓</i><div><small>MEASURABLE IMPACT</small><div className="ev-delta-grid"><Delta label="Cash" before={consequence.before.business.cash} after={consequence.after.business.cash} format="money" /><Delta label="Revenue" before={consequence.before.business.revenue} after={consequence.after.business.revenue} format="money" /><Delta label="Market share" before={consequence.before.business.marketShare} after={consequence.after.business.marketShare} format="percent" /></div></div></div><div className="ev-consequence-explanation"><span className="ev-kicker">WHY THIS MATTERS</span><h3>{committedDebrief.consequence}</h3><p>{committedDebrief.lesson}</p></div><div className="ev-causal-footer"><span>DECISION</span><i>→</i><span>BUSINESS ACTION</span><i>→</i><span>SIMULATION RESPONSE</span><i>→</i><span>NEW STATE</span></div></section>}
    <section className="ev-learning"><div><span className="ev-kicker">CONTEXTUAL LEARNING</span><h2>{committedDebrief?.lesson ?? "Your first lesson is already inside the simulation."}</h2><p>{committedDebrief ? `You just experienced this through ${state.business.name}. The concept matters because it changed a real decision, not because it appeared in a lesson list.` : "When a concept appears in the simulation, connect it to the actual outcome and carry that understanding into the next decision."}</p></div><div className="ev-learning-mini"><span>FOUNDER PROGRESS</span><strong>{learning.overallScore}/100</strong><small>{progress.xp} XP · Level {progress.level}</small></div></section>
    <div className="ev-day-footer"><button type="button" className="ev-secondary" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}>Review company ↑</button>{consequence ? <button type="button" className="ev-primary" onClick={() => void continueDay()}>Continue to the next day →</button> : <Link className="ev-secondary ev-link-button" href="/learning">Open learning workspace →</Link>}</div>
  </CanonicalShell>;
}
