"use client";

type Session = { access_token: string };
export type CareerProfile = { progress: { xp: number; level: number; skills: Record<string, number>; milestones: unknown[]; reputation: number; market_value: number; career_summary: Record<string, unknown> }; profile: { user_id: string; display_name: string; current_business_id: string | null; active_role: string | null; preferred_role: string | null }; history: Array<{ id: string; business_id: string | null; company_name: string; role: string; started_at: string; ended_at: string | null; performance_score: number; summary: string }>; offers: Array<{ id: string; business_id: string; role: string; compensation: number; reason: string; status: string; created_at: string; company: { id: string; name: string; industry: string | null; stage: string; company_level: number } }> };
export type Candidate = { user_id: string; display_name: string; current_company_name: string | null; current_company_level: number | null; career_level: number; experience_points: number; reputation: number; role_fit: number; skills: Record<string, number> };

const url = process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/, "") ?? "";
const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? "";
const SESSION_KEY = "enterpriseverse:supabase-session:v1";
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function session(): Session | null { try { const raw = typeof window !== "undefined" ? window.localStorage.getItem(SESSION_KEY) : null; return raw ? JSON.parse(raw) as Session : null; } catch { return null; } }
function uuid(value: string) { if (!UUID_RE.test(value.trim())) throw new Error("Invalid ID."); return value.trim(); }
async function request<T>(path: string, init: RequestInit = {}) { const current = session(); if (!url || !anonKey || !current?.access_token) throw new Error("Sign in to continue."); const controller = new AbortController(); const timeout = window.setTimeout(() => controller.abort(), 12000); const headers = new Headers(init.headers); headers.set("apikey", anonKey); headers.set("Authorization", `Bearer ${current.access_token}`); headers.set("Content-Type", "application/json"); try { const response = await fetch(`${url}${path}`, { ...init, headers, cache: "no-store", signal: controller.signal }); const raw = await response.text(); let body: unknown = null; try { body = raw ? JSON.parse(raw) : null; } catch { body = raw; } if (!response.ok) throw new Error(typeof body === "object" && body !== null && "message" in body && typeof body.message === "string" ? body.message : `Career request failed (${response.status}).`); return body as T; } finally { window.clearTimeout(timeout); } }
export function loadCareerProfile() { return request<CareerProfile | null>("/rest/v1/rpc/get_career_profile", { method: "POST", body: "{}" }); }
export function searchRecruitablePlayers(businessId: string, role: string, query: string) { return request<Candidate[]>("/rest/v1/rpc/search_recruitable_players", { method: "POST", body: JSON.stringify({ p_business_id: uuid(businessId), p_role: role, p_query: query.trim() }) }); }
export function createRecruitmentOffer(args: { businessId: string; candidateId: string; positionId: string; compensation: number; reason: string }) { return request<string>("/rest/v1/rpc/create_recruitment_offer", { method: "POST", body: JSON.stringify({ p_business_id: uuid(args.businessId), p_candidate_id: uuid(args.candidateId), p_position_id: uuid(args.positionId), p_compensation: args.compensation, p_reason: args.reason.trim() }) }); }
export function respondRecruitmentOffer(offerId: string, action: "accept" | "decline") { return request<string>("/rest/v1/rpc/respond_recruitment_offer", { method: "POST", body: JSON.stringify({ p_offer_id: uuid(offerId), p_action: action }) }); }
export function loadNotificationCenter() { return request<{ notifications: Array<{ id: string; type: string; title: string; body: string; read_at: string | null; metadata: Record<string, unknown>; created_at: string }>; unread_count: number }>("/rest/v1/rpc/get_notification_center", { method: "POST", body: "{}" }); }
export function markNotificationCenterRead(notificationId: string) { return request<boolean>("/rest/v1/rpc/mark_notification_center_read", { method: "POST", body: JSON.stringify({ p_notification_id: uuid(notificationId) }) }); }
